//! A port of [`github.com/gobwas/glob`](https://github.com/gobwas/glob) v0.2.3,
//! the glob library Tanka links.
//!
//! This is a deliberate Go-library port, in the spirit of `rtk-masterminds`:
//! its whole purpose is behavioural equivalence, so it is checked against a
//! truth table generated by the Go library itself
//! (`testdata/`, with its generator beside it).
//!
//! # Why not `globset`
//!
//! `tk` compiles its `--exclude` patterns with `glob.Compile(e)` — no separator
//! arguments. With no separators `gobwas` treats `*` and `**` alike, so **`*`
//! crosses `/`**. `globset` does not behave this way, and reaching for it
//! silently changes which files `rtk fmt` and `rtk lint` touch. That is also
//! why `tk`'s default exclude list ships each pattern twice (`".*"` *and*
//! `"**/.*"`): the un-prefixed form catches the case where the string being
//! matched has no leading directory component.
//!
//! # Syntax
//!
//! ```text
//! *           any sequence of non-separator characters
//! **          any sequence of characters
//! ?           any single non-separator character
//! [ [!] ... ] character class, e.g. [abc] or [a-z] or [!0-9]
//! { a, b }    alternatives
//! \c          the literal c
//! ```

mod ast;
mod lexer;
mod program;

pub use lexer::quote_meta;
use program::Program;

/// A pattern `gobwas/glob` would have rejected.
///
/// The message is the Go one verbatim, because `tk fmt` prints whatever
/// `glob.Compile` returns.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("{message}")]
pub struct Error {
	message: String,
}

impl Error {
	fn new(message: String) -> Self {
		Self { message }
	}

	/// The message, without the `Display` wrapper.
	pub fn message(&self) -> &str {
		&self.message
	}
}

/// A compiled glob pattern.
#[derive(Debug, Clone)]
pub struct Glob {
	program: Program,
}

impl Glob {
	/// Compile `pattern` with no separators — the way `tk` compiles its
	/// `--exclude` patterns, where `*` crosses `/`.
	pub fn new(pattern: &str) -> Result<Self, Error> {
		Self::with_separators(pattern, &[])
	}

	/// Compile `pattern`, treating each of `separators` as a character that
	/// `*` and `?` will not cross.
	pub fn with_separators(pattern: &str, separators: &[char]) -> Result<Self, Error> {
		let tree = ast::parse(pattern).map_err(Error::new)?;
		Ok(Self {
			program: Program::compile(&tree, separators),
		})
	}

	/// Whether the whole of `subject` matches.
	pub fn is_match(&self, subject: &str) -> bool {
		self.program.is_match(subject)
	}
}

/// Compile every pattern, in order, failing on the first one `gobwas` would
/// have rejected.
///
/// This is `tk fmt`'s own loop over `--exclude`.
pub fn compile_all<I, S>(patterns: I) -> Result<Vec<Glob>, Error>
where
	I: IntoIterator<Item = S>,
	S: AsRef<str>,
{
	patterns
		.into_iter()
		.map(|pattern| Glob::new(pattern.as_ref()))
		.collect()
}

/// `tk`'s default `--exclude` list, from `cmd/tk/fmt.go` and `cmd/tk/lint.go`.
///
/// The order is upstream's, and each pattern appears in both its bare and its
/// `**/`-prefixed form on purpose — see the crate documentation.
pub const TANKA_DEFAULT_EXCLUDES: [&str; 4] = ["**/.*", ".*", "**/vendor/**", "vendor/**"];

#[cfg(test)]
mod tests {
	use super::*;

	fn matches(pattern: &str, subject: &str) -> bool {
		Glob::new(pattern)
			.expect("pattern compiles")
			.is_match(subject)
	}

	#[test]
	fn star_crosses_slash_without_separators() {
		// The behaviour `globset` would get wrong.
		assert!(matches("*", "a/b/c"));
		assert!(matches("vendor/**", "vendor/a/b.libsonnet"));
		assert!(matches(".*", ".git/config"));
	}

	#[test]
	fn star_stops_at_a_declared_separator() {
		let glob = Glob::with_separators("*", &['/']).expect("pattern compiles");
		assert!(glob.is_match("abc"));
		assert!(!glob.is_match("a/b"));

		let glob = Glob::with_separators("**", &['/']).expect("pattern compiles");
		assert!(glob.is_match("a/b"));
	}

	#[test]
	fn tanka_defaults_need_both_forms() {
		let bare = Glob::new("vendor/**").expect("pattern compiles");
		let prefixed = Glob::new("**/vendor/**").expect("pattern compiles");

		// A match string with no leading directory component is caught only by
		// the bare form: `**/vendor/**` wants a literal "/vendor/" somewhere,
		// and there is none.
		assert!(bare.is_match("vendor/k.libsonnet"));
		assert!(!prefixed.is_match("vendor/k.libsonnet"));

		// A nested vendor directory is caught only by the prefixed form, since
		// the bare one anchors "vendor/" at the start.
		assert!(!bare.is_match("environments/vendor/k.libsonnet"));
		assert!(prefixed.is_match("environments/vendor/k.libsonnet"));
	}

	#[test]
	fn single_matches_exactly_one_character() {
		assert!(matches("a?c", "abc"));
		assert!(!matches("a?c", "ac"));
		assert!(!matches("a?c", "abbc"));
	}

	#[test]
	fn character_classes_and_ranges() {
		assert!(matches("[abc]", "b"));
		assert!(!matches("[abc]", "d"));
		assert!(matches("[!abc]", "d"));
		assert!(matches("[a-z]", "q"));
		assert!(!matches("[a-z]", "Q"));
		assert!(matches("[!a-z]", "Q"));
	}

	#[test]
	fn alternation() {
		assert!(matches("{a,b}c", "ac"));
		assert!(matches("{a,b}c", "bc"));
		assert!(!matches("{a,b}c", "cc"));
		// An empty alternative matches nothing at all, not "no match".
		assert!(matches("{,a}b", "b"));
		assert!(matches("{,a}b", "ab"));
	}

	#[test]
	fn escapes_take_the_metacharacter_literally() {
		assert!(matches(r"a\*b", "a*b"));
		assert!(!matches(r"a\*b", "axb"));
		assert!(matches(r"\[a\]", "[a]"));
	}

	#[test]
	fn the_empty_subject_follows_gobwas_rather_than_intuition() {
		// Every assertion here came from the generated truth table, not from
		// reasoning about what the patterns ought to mean. `?` matches the
		// empty string because `gobwas` decodes `(RuneError, 0)` from it and
		// its `len(s) > w` guard lets that through, so U+FFFD gets tested for
		// membership.
		assert!(matches("?", ""));
		assert!(matches("[!abc]", ""));
		assert!(!matches("[abc]", ""));

		// ...but only where the compiler reduced the pattern to that one
		// matcher. Anything composite becomes a `BTree`, whose match loop does
		// not run at all on empty input.
		assert!(!matches("??", ""));
		assert!(!matches("a?", ""));

		// A run of `Any`/`Super` sharing one separator set is collapsed into a
		// single matcher, so it is back in the first case.
		assert!(matches("", ""));
		assert!(matches("**", ""));
		assert!(matches("***", ""));

		// Declare a separator and `***` is `Super` followed by `Any('/')`,
		// which cannot be collapsed — so the same pattern stops matching.
		let glob = Glob::with_separators("***", &['/']).expect("pattern compiles");
		assert!(!glob.is_match(""));
	}

	#[test]
	fn whole_subject_must_match() {
		assert!(!matches("abc", "abcd"));
		assert!(!matches("abc", "xabc"));
	}

	#[test]
	fn quote_meta_escapes_every_special() {
		assert_eq!(quote_meta("{foo*}"), r"\{foo\*\}");
	}

	#[test]
	fn unterminated_range_is_the_go_error() {
		let err = Glob::new("[a").expect_err("pattern is rejected");
		assert_eq!(err.message(), "unexpected end of input");
	}

	#[test]
	fn inverted_range_is_the_go_error() {
		let err = Glob::new("[z-a]").expect_err("pattern is rejected");
		assert_eq!(
			err.message(),
			"hi character 'a' should be greater than lo 'z'"
		);
	}

	#[test]
	fn compile_all_fails_on_the_first_bad_pattern() {
		let err = compile_all(["*", "[a", "**"]).expect_err("one pattern is rejected");
		assert_eq!(err.message(), "unexpected end of input");
	}

	#[test]
	fn default_excludes_compile() {
		let globs = compile_all(TANKA_DEFAULT_EXCLUDES).expect("defaults compile");
		assert_eq!(globs.len(), 4);
	}
}
