//! A port of `sort.Slice` from Go's standard library.
//!
//! Not a sorting utility. This exists because **sorting has more than one
//! right answer**, and `rtk fmt` has to give the same one `tk fmt` gives.
//!
//! # Why a port rather than `sort_by`
//!
//! `SortImports` sorts a group of imports by path, and two imports may share a
//! path — `local k = import 'k.libsonnet', kausal = import 'k.libsonnet';` is
//! an ordinary Jsonnet habit. "Sorted" says nothing about which of those two
//! comes first, so the sort's tie behaviour decides what is written to the
//! file, and Go's and Rust's disagree.
//!
//! The oracle measured it rather than the documentation being trusted. Over
//! the `sort_imports/ties_*` snippets, `sort.Slice` inverts ties from **n = 13**
//! upwards: a group of thirteen whose first and last element share a key comes
//! back with the last one first, and a run of three sharing a key comes back
//! `i09 i01 i04`. Below that it is stable by accident, because
//! `LessSwap::sort`'s `MAX_INSERTION` is 12 tested with `<=`, so twelve is
//! the *last* size that is insertion-sorted rather than the first that is not.
//! Reading the constant as a strict bound puts the boundary one out.
//!
//! So `Vec::sort_by` is measurably wrong here, and `sort_unstable_by` — which
//! is also a pdqsort — is a different implementation with different pivot
//! choices and is wrong differently. The only thing that matches is Go's.
//!
//! This is the third deliberate Go-library port in the repository, and it is
//! here for the same reason as the other two: `rtk-gobwas-glob` exists because
//! `*` crosses `/` in gobwas and does not in `globset`, and
//! `rtk-masterminds` exists because a bare `1.2.3` is *equality* in
//! Masterminds and a caret to the `semver` crate. A crate that does the job
//! well but not identically is not usable when identical is the contract.
//!
//! # What it is a port of, exactly
//!
//! `sort.Slice` in `sort/slice.go`, which is four lines around
//! `pdqsort_func(lessSwap{less, swap}, 0, length, bits.Len(uint(length)))`,
//! and the `_func` family in `sort/zsortfunc.go` that it reaches. That file is
//! generated by `gen_sort_variants.go` from one template, so the `_func`,
//! `_Interface` and `_ordered` variants are the same algorithm; porting one
//! ports the behaviour of all three.
//!
//! Every step is a method on `LessSwap` — Go's own struct of that name —
//! rather than a free function, because `data` is the primary state each one
//! mutates and Go's `data lessSwap` first parameter is exactly that state
//! passed explicitly. Go writes them as functions only because it has no
//! other way to generate three variants from one template.
//!
//! # The one honest caveat
//!
//! `sort.Slice` is documented as *not* stable, so this tie order is an
//! implementation detail of the Go toolchain that built `tk`, not a promise.
//! It has been pdqsort since Go 1.19 and the generated file has not moved
//! since, but a future Go could reorder ties and `tk fmt`'s output would move
//! with it while rtk's did not. That is a reason to keep the truth table
//! regenerable — `make update-go-sort-truth-table` records the Go version that
//! produced it — not a reason to sort differently, because there is no
//! third answer that is more correct than the one `tk` actually prints.
//!
//! # Graded by
//!
//! - `testdata/go-sort-truth-table.json`, generated by the Go standard library
//!   itself over ten input shapes at thirty-nine lengths, which is what reaches
//!   the heapsort fallback and `LessSwap::break_patterns` that no realistic
//!   import group does.
//! - the `sort_imports/ties_*` snippets, end to end, through the pass oracle.
//!
//! The table records only the **permutation**, over integer keys. String
//! comparison is graded separately and does not need a table: Go's `<` on
//! `string` and Rust's `Ord` on `str` are both bytewise, and the
//! `sort_imports/case_is_bytewise` and
//! `sort_imports/punctuation_sorts_before_letters` snippets pin that through
//! the real comparator.

// Go's own names are one and two letters — `a`, `b`, `i`, `j`, `k`, `lo`,
// `hi`, `mid`. They are kept, because the value of a port is that it can be
// read against its original line by line, and renaming them to `start` and
// `end` would make every comparison with `zsortfunc.go` a translation
// exercise.
#![allow(clippy::many_single_char_names)]

/// `sort.sortedHint`: what `LessSwap::choose_pivot` noticed on its way to a
/// pivot.
///
/// The variants are Go's `unknownHint`, `increasingHint` and `decreasingHint`,
/// which are an `iota` block and so carry no meaning beyond their identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum SortedHint {
	Unknown,
	Increasing,
	Decreasing,
}

/// `sort.xorshift`: the deterministic generator
/// `LessSwap::break_patterns` scatters elements with.
///
/// Deterministic is the load-bearing word. It is seeded from the length of the
/// range being sorted and nothing else, so the same input always produces the
/// same permutation — which is what makes a formatter that depends on it
/// reproducible at all.
struct Xorshift(u64);

impl Xorshift {
	/// `xorshift(length)`, which is a conversion rather than a constructor.
	fn seeded(length: usize) -> Self {
		Self(u64::try_from(length).expect("a slice length fits in a u64"))
	}

	/// `(*xorshift).Next`.
	///
	/// Named `draw` rather than `next` so it is not mistaken for
	/// [`Iterator::next`]; it is not an iterator and never terminates.
	fn draw(&mut self) -> u64 {
		self.0 ^= self.0 << 13;
		self.0 ^= self.0 >> 7;
		self.0 ^= self.0 << 17;
		self.0
	}
}

/// `sort.nextPowerOfTwo`.
///
/// **Not the least power of two at least `length`.** Go computes
/// `1 << bits.Len(uint(length))`, so an exact power of two is rounded *up*
/// again: `next_power_of_two(8)` is 16. `LessSwap::break_patterns` only uses
/// it as a mask, so the doubling is harmless there — but it is not what the
/// name says, and `usize::next_power_of_two` is a different function.
fn next_power_of_two(length: usize) -> u64 {
	let bits_len = usize::BITS - length.leading_zeros();
	// Go would need a length of 2^63 to shift by 64 here, which no slice
	// reaches; both languages are equally undefined there.
	1u64 << bits_len
}

/// Go's `lessSwap`: the slice being sorted, plus the comparison.
///
/// Go's closure indexes the live slice, so `Less(i, j)` always reads the
/// *current* occupants of those positions rather than the elements that
/// started there. That is why this holds `&mut [T]` and compares through
/// indices instead of taking the comparator over owned keys — the sequence of
/// comparisons, and so the permutation, depends on it.
struct LessSwap<'data, T, F> {
	data: &'data mut [T],
	predicate: F,
}

impl<T, F: Fn(&T, &T) -> bool> LessSwap<'_, T, F> {
	/// `lessSwap.Less`.
	fn less(&self, i: usize, j: usize) -> bool {
		(self.predicate)(&self.data[i], &self.data[j])
	}

	/// `lessSwap.Swap`.
	fn swap(&mut self, i: usize, j: usize) {
		self.data.swap(i, j);
	}

	/// `insertionSort_func`: sorts `data[a..b]`.
	fn insertion_sort(&mut self, a: usize, b: usize) {
		for i in (a + 1)..b {
			let mut j = i;
			while j > a && self.less(j, j - 1) {
				self.swap(j, j - 1);
				j -= 1;
			}
		}
	}

	/// `siftDown_func`: restores the heap property on `data[lo..hi]`, with
	/// `first` the offset at which the heap's root lives.
	fn sift_down(&mut self, lo: usize, hi: usize, first: usize) {
		let mut root = lo;
		loop {
			let mut child = 2 * root + 1;
			if child >= hi {
				break;
			}
			if child + 1 < hi && self.less(first + child, first + child + 1) {
				child += 1;
			}
			if !self.less(first + root, first + child) {
				return;
			}
			self.swap(first + root, first + child);
			root = child;
		}
	}

	/// `heapSort_func`: the fallback when too many pivots were bad.
	///
	/// Reached only through `LessSwap::sort`'s `limit == 0`, which needs
	/// `bits.Len(n)` consecutive unbalanced partitions. No import group gets
	/// near it; the truth table does.
	fn heap_sort(&mut self, a: usize, b: usize) {
		let first = a;
		let lo = 0;
		let hi = b - a;

		// Go writes `for i := (hi - 1) / 2; i >= 0; i--`, which in Rust would
		// be an unsigned loop that never ends. `hi` is at least 13 here,
		// because nothing shorter than that reaches heapsort.
		for i in (0..=(hi - 1) / 2).rev() {
			self.sift_down(i, hi, first);
		}

		for i in (0..hi).rev() {
			self.swap(first, first + i);
			self.sift_down(lo, i, first);
		}
	}

	/// `partition_func`: one quicksort partition around `data[pivot]`.
	///
	/// Returns the pivot's new position and whether the range was already
	/// partitioned, which `LessSwap::sort` carries forward as
	/// `wasPartitioned`.
	fn partition(&mut self, a: usize, b: usize, pivot: usize) -> (usize, bool) {
		self.swap(a, pivot);
		// Inclusive of the elements remaining to be partitioned, which is why
		// the loops test `i <= j` rather than `i < j`.
		let (mut i, mut j) = (a + 1, b - 1);

		while i <= j && self.less(i, a) {
			i += 1;
		}
		while i <= j && !self.less(j, a) {
			j -= 1;
		}
		if i > j {
			self.swap(j, a);
			return (j, true);
		}
		self.swap(i, j);
		i += 1;
		j -= 1;

		loop {
			while i <= j && self.less(i, a) {
				i += 1;
			}
			while i <= j && !self.less(j, a) {
				j -= 1;
			}
			if i > j {
				break;
			}
			self.swap(i, j);
			i += 1;
			j -= 1;
		}
		self.swap(j, a);
		(j, false)
	}

	/// `partitionEqual_func`: splits `data[a..b]` into elements equal to
	/// `data[pivot]` and elements greater, assuming none is smaller.
	///
	/// This is the branch that makes an all-equal range come back in source
	/// order, which is why every `ties_*_all_equal` snippet is a no-op while
	/// the mixed arrangements are not.
	fn partition_equal(&mut self, a: usize, b: usize, pivot: usize) -> usize {
		self.swap(a, pivot);
		let (mut i, mut j) = (a + 1, b - 1);

		loop {
			while i <= j && !self.less(a, i) {
				i += 1;
			}
			while i <= j && self.less(a, j) {
				j -= 1;
			}
			if i > j {
				break;
			}
			self.swap(i, j);
			i += 1;
			j -= 1;
		}
		i
	}

	/// `partialInsertionSort_func`: shifts at most five out-of-order pairs, and
	/// reports whether the range came out sorted.
	///
	/// One upstream oddity is reproduced here: the left-shifting loop is
	/// `for j := i - 1; j >= 1; j--`, bounded by the **literal 1** and not by
	/// `a`. On a recursive call with `a > 0` it can therefore walk below the
	/// range it was given. Reproduced rather than corrected — it is what `tk`
	/// runs.
	fn partial_insertion_sort(&mut self, a: usize, b: usize) -> bool {
		const MAX_STEPS: usize = 5;
		const SHORTEST_SHIFTING: usize = 50;

		let mut i = a + 1;
		for _step in 0..MAX_STEPS {
			while i < b && !self.less(i, i - 1) {
				i += 1;
			}

			if i == b {
				return true;
			}

			if b - a < SHORTEST_SHIFTING {
				return false;
			}

			self.swap(i, i - 1);

			// Shift the smaller one to the left.
			if i - a >= 2 {
				let mut j = i - 1;
				while j >= 1 {
					if !self.less(j, j - 1) {
						break;
					}
					self.swap(j, j - 1);
					j -= 1;
				}
			}
			// Shift the greater one to the right.
			if b - i >= 2 {
				for j in (i + 1)..b {
					if !self.less(j, j - 1) {
						break;
					}
					self.swap(j, j - 1);
				}
			}
		}
		false
	}

	/// `breakPatterns_func`: scatters three elements to spoil an input shaped
	/// to make quicksort degenerate.
	fn break_patterns(&mut self, a: usize, b: usize) {
		let length = b - a;
		if length >= 8 {
			let mut random = Xorshift::seeded(length);
			let mask = next_power_of_two(length) - 1;

			let middle = a + (length / 4) * 2;
			for idx in (middle - 1)..=(middle + 1) {
				let drawn = random.draw() & mask;
				// The mask is derived from the length, so the draw is below
				// `next_power_of_two(length)` and fits a usize on every
				// platform this runs on.
				let mut other =
					usize::try_from(drawn).expect("masked below a length-derived bound");
				if other >= length {
					other -= length;
				}
				self.swap(idx, a + other);
			}
		}
	}

	/// `choosePivot_func`.
	///
	/// Three regimes, by length: a static pivot below 8, a median of three
	/// below `shortestNinther`, and Tukey's ninther — a median of three
	/// medians of three — at 50 and above. The `swaps` count is how the hint
	/// is derived: none means the samples were already increasing, all twelve
	/// means they were decreasing.
	fn choose_pivot(&self, a: usize, b: usize) -> (usize, SortedHint) {
		const SHORTEST_NINTHER: usize = 50;
		const MAX_SWAPS: usize = 4 * 3;

		let l = b - a;

		let mut swaps = 0;
		let mut i = a + l / 4;
		let mut j = a + l / 4 * 2;
		let mut k = a + l / 4 * 3;

		if l >= 8 {
			if l >= SHORTEST_NINTHER {
				i = self.median_adjacent(i, &mut swaps);
				j = self.median_adjacent(j, &mut swaps);
				k = self.median_adjacent(k, &mut swaps);
			}
			// Find the median among i, j, k and store it in j.
			j = self.median(i, j, k, &mut swaps);
		}

		match swaps {
			0 => (j, SortedHint::Increasing),
			MAX_SWAPS => (j, SortedHint::Decreasing),
			_ => (j, SortedHint::Unknown),
		}
	}

	/// `order2_func`: the pair reordered so the first indexes the smaller.
	///
	/// It swaps nothing despite the name — it returns indices and counts how
	/// often it had to exchange them.
	fn order2(&self, a: usize, b: usize, swaps: &mut usize) -> (usize, usize) {
		if self.less(b, a) {
			*swaps += 1;
			return (b, a);
		}
		(a, b)
	}

	/// `median_func`: whichever of `a`, `b`, `c` indexes the median value.
	///
	/// Three `LessSwap::order2` calls, and the third reassigns both `a` and
	/// `b`. `c` is dead after the second, exactly as it is in Go — the
	/// assignment is there so the sequence of comparisons, and so the `swaps`
	/// count, is the one the hint is derived from.
	fn median(&self, a: usize, b: usize, c: usize, swaps: &mut usize) -> usize {
		let (a, b) = self.order2(a, b, swaps);
		let (b, _c) = self.order2(b, c, swaps);
		let (_a, b) = self.order2(a, b, swaps);
		b
	}

	/// `medianAdjacent_func`: the median of `a - 1`, `a` and `a + 1`.
	fn median_adjacent(&self, a: usize, swaps: &mut usize) -> usize {
		self.median(a - 1, a, a + 1, swaps)
	}

	/// `reverseRange_func`.
	fn reverse_range(&mut self, a: usize, b: usize) {
		let mut i = a;
		let mut j = b - 1;
		while i < j {
			self.swap(i, j);
			i += 1;
			j -= 1;
		}
	}

	/// `pdqsort_func`: pattern-defeating quicksort over `data[a..b]`.
	///
	/// `limit` is how many badly unbalanced pivots are tolerated before
	/// falling back to `LessSwap::heap_sort`; `sort.Slice` seeds it with
	/// `bits.Len(uint(length))`.
	fn sort(&mut self, mut a: usize, mut b: usize, mut limit: usize) {
		const MAX_INSERTION: usize = 12;

		// Whether the last partitioning was reasonably balanced, and whether
		// the range was already partitioned. Both start optimistic, which is
		// what lets `partialInsertionSort` be tried on the first round.
		let mut was_balanced = true;
		let mut was_partitioned = true;

		loop {
			let length = b - a;

			// `<=`, so twelve is the last insertion-sorted size and thirteen
			// the first that can reorder ties. The whole of this module exists
			// because of that boundary.
			if length <= MAX_INSERTION {
				self.insertion_sort(a, b);
				return;
			}

			if limit == 0 {
				self.heap_sort(a, b);
				return;
			}

			if !was_balanced {
				self.break_patterns(a, b);
				limit -= 1;
			}

			let (mut pivot, mut hint) = self.choose_pivot(a, b);
			if hint == SortedHint::Decreasing {
				self.reverse_range(a, b);
				// The pivot was `pivot - a` elements after the start; after
				// reversing it is that many before the end.
				pivot = (b - 1) - (pivot - a);
				hint = SortedHint::Increasing;
			}

			// Upstream nests this as two `if`s; collapsing is the same
			// short-circuit and the same sequence of comparisons.
			if was_balanced
				&& was_partitioned
				&& hint == SortedHint::Increasing
				&& self.partial_insertion_sort(a, b)
			{
				return;
			}

			// Probably many duplicates: split into equal-to and greater-than.
			if a > 0 && !self.less(a - 1, pivot) {
				a = self.partition_equal(a, b, pivot);
				continue;
			}

			let (mid, already_partitioned) = self.partition(a, b, pivot);
			was_partitioned = already_partitioned;

			let (left_len, right_len) = (mid - a, b - mid);
			let balance_threshold = length / 8;
			if left_len < right_len {
				was_balanced = left_len >= balance_threshold;
				self.sort(a, mid, limit);
				a = mid + 1;
			} else {
				was_balanced = right_len >= balance_threshold;
				self.sort(mid + 1, b, limit);
				b = mid;
			}
		}
	}
}

/// `sort.Slice`: sorts `data` by `less`, with Go's tie order.
///
/// `less(x, y)` answers Go's `less(i, j)` for the elements currently at those
/// positions. The sort is not stable, and reproducing *which* unstable answer
/// is the point — see the module documentation.
pub fn slice<T, F: Fn(&T, &T) -> bool>(data: &mut [T], less: F) {
	let length = data.len();
	// `bits.Len(uint(length))`, and `bits.Len(0)` is 0.
	let limit = (usize::BITS - length.leading_zeros()) as usize;
	let mut data = LessSwap {
		data,
		predicate: less,
	};
	data.sort(0, length, limit);
}

#[cfg(test)]
mod tests {
	use super::*;

	/// Sort `keys` and report where each element came from, which is the
	/// notation `testdata/go-sort-truth-table.json` records.
	fn permutation(keys: &[i64]) -> Vec<usize> {
		let mut indexed: Vec<(i64, usize)> = keys.iter().copied().zip(0..).collect();
		slice(&mut indexed, |left, right| left.0 < right.0);
		indexed.into_iter().map(|(_, at)| at).collect()
	}

	#[test]
	fn it_sorts() {
		for length in 0..40usize {
			// Descending, so every length has something to do.
			let keys: Vec<i64> = (0..length)
				.map(|at| -i64::try_from(at).expect("a test index fits in an i64"))
				.collect();
			let order = permutation(&keys);
			let sorted: Vec<i64> = order.iter().map(|&at| keys[at]).collect();
			assert!(
				sorted.windows(2).all(|pair| pair[0] <= pair[1]),
				"length {length} came out unsorted: {sorted:?}"
			);
			assert_eq!(order.len(), length);
		}
	}

	#[test]
	fn ties_are_stable_up_to_twelve_and_not_at_thirteen() {
		// The measured boundary, and the reason this module exists. Twelve is
		// `maxInsertion` tested with `<=`, so it is the last size that leaves
		// insertion sort; thirteen is the first that reaches pdqsort proper.
		// The arrangement is the `sort_imports/ties_thirteen_at_the_ends`
		// snippet's: the tie is the first and last element.
		let stable_at_twelve = permutation(&[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0]);
		assert_eq!(
			stable_at_twelve,
			vec![0, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
			"twelve elements are insertion-sorted, so the tie keeps source order"
		);

		let at_thirteen = permutation(&[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0]);
		assert_eq!(
			at_thirteen[0], 12,
			"at thirteen the tie inverts: the *last* element sorts first, which \
			 is what the ties_thirteen_at_the_ends snippet shows end to end"
		);
	}

	#[test]
	fn an_all_equal_range_keeps_its_order_at_every_length() {
		// `partitionEqual` is what makes this true, and it is why every
		// `ties_*_all_equal` snippet is recorded as a no-op while the mixed
		// arrangements are not. If this ever fails, the port of that branch is
		// wrong and the snippets will say so too.
		for length in 0..60usize {
			let keys = vec![0i64; length];
			let order = permutation(&keys);
			assert_eq!(
				order,
				(0..length).collect::<Vec<_>>(),
				"all-equal range of {length} was reordered"
			);
		}
	}

	#[test]
	fn empty_and_single_element_slices_are_left_alone() {
		assert_eq!(permutation(&[]), Vec::<usize>::new());
		assert_eq!(permutation(&[7]), vec![0]);
	}

	#[test]
	fn next_power_of_two_rounds_an_exact_power_up_again() {
		// Not what the name says, and `usize::next_power_of_two` disagrees.
		assert_eq!(next_power_of_two(8), 16);
		assert_eq!(next_power_of_two(7), 8);
		assert_eq!(next_power_of_two(1), 2);
		assert_eq!(next_power_of_two(0), 1);
	}

	#[test]
	fn the_xorshift_is_seeded_only_by_the_length() {
		// Determinism is what makes a formatter that reaches `breakPatterns`
		// reproducible, so it is asserted rather than assumed.
		let mut first = Xorshift::seeded(64);
		let mut second = Xorshift::seeded(64);
		for _ in 0..8 {
			assert_eq!(first.draw(), second.draw());
		}
		assert_ne!(Xorshift::seeded(64).draw(), Xorshift::seeded(65).draw());
	}
}
