//! A port of go-jsonnet's `internal/formatter/unparser.go`, fodder first.
//!
//! The unparser is what turns the formatted AST back into text. Only the fodder
//! half is here: [`Unparser::fill`] and its variants, which render a [`Fodder`]
//! and decide whether a space is needed to keep two tokens apart. The rest of
//! the unparser walks the AST, so it lands with the AST.
//!
//! Everything about this file is worth reading as *generation*, not
//! reproduction. The text comes out of the fodder model, so:
//!
//! - a line-end comment is always preceded by exactly **two** spaces, whatever
//!   the author wrote
//! - indentation is `indent` spaces, and the lexer counted a tab as 8
//! - blank lines are `blanks` newlines
//!
//! That is why `unparse(parse(x)) == x` does not hold, and why the Phase 2a
//! gate is a corpus generated by go-jsonnet rather than a round trip.

use crate::{
	Options,
	ast::{
		ForSpec, FunctionSugar, LiteralString, LiteralStringKind, Node, NodeKind, ObjectField,
		ObjectFieldHide, ObjectFieldKind, Parameter,
	},
	fodder::{Fodder, FodderKind},
};

/// Accumulates output. `go-jsonnet`'s `unparser`.
pub struct Unparser {
	buf: String,
	options: Options,
}

impl Unparser {
	pub fn new(options: Options) -> Self {
		Self {
			buf: String::new(),
			options,
		}
	}

	/// The options this unparser renders with.
	///
	/// `PadArrays` and `PadObjects` are consumed here rather than by any pass,
	/// which is why the unparser needs them at all.
	pub fn options(&self) -> &Options {
		&self.options
	}

	pub fn write(&mut self, text: &str) {
		self.buf.push_str(text);
	}

	fn write_spaces(&mut self, count: usize) {
		for _ in 0..count {
			self.buf.push(' ');
		}
	}

	fn write_newlines(&mut self, count: usize) {
		for _ in 0..count {
			self.buf.push('\n');
		}
	}

	/// Pretty-print fodder. Go's `fodderFill`.
	///
	/// `crowded` and `separate_token` control the single spaces that keep
	/// tokens from running together, and the caller's intent is captured by
	/// Go's own explanation: pass `crowded` when the last thing printed would
	/// crowd whatever comes next — true after a `,`, false after a `(`, since
	/// no space is wanted there. The four combinations behave as:
	///
	/// | `crowded` | `separate_token` | result |
	/// | --- | --- | --- |
	/// | true | true | a space after the fodder, unless it ended with a newline |
	/// | true | false | a leading space before an opening interstitial, none after |
	/// | false | true | a space only if the fodder ended with an interstitial |
	/// | false | false | no space on either side, interstitial or not |
	///
	/// `is_final` suppresses the blanks and indent of the **last** element,
	/// which is how the trailing fodder of a file avoids emitting the
	/// indentation of a line that will never be written.
	fn fodder_fill(
		&mut self,
		fodder: &Fodder,
		mut crowded: bool,
		separate_token: bool,
		is_final: bool,
	) {
		let mut last_indent = 0;
		let count = fodder.len();

		for (index, element) in fodder.iter().enumerate() {
			let skip_trailing = is_final && index == count - 1;

			match element.kind {
				FodderKind::Paragraph => {
					for (line_index, line) in element.comment.iter().enumerate() {
						// An empty line is not indented. The first line never
						// is either, because the previous element already
						// emitted this line's indentation.
						if !line.is_empty() {
							if line_index > 0 {
								self.write_spaces(last_indent);
							}
							self.buf.push_str(line);
						}
						self.write("\n");
					}
					if !skip_trailing {
						self.write_newlines(element.blanks);
						self.write_spaces(element.indent);
					}
					last_indent = element.indent;
					crowded = false;
				}

				FodderKind::LineEnd => {
					if let Some(comment) = element.comment.first() {
						// Always two spaces, whatever the source had.
						self.buf.push_str("  ");
						self.buf.push_str(comment);
					}
					self.write("\n");
					if !skip_trailing {
						self.write_newlines(element.blanks);
						self.write_spaces(element.indent);
					}
					last_indent = element.indent;
					crowded = false;
				}

				FodderKind::Interstitial => {
					if crowded {
						self.write(" ");
					}
					self.buf.push_str(
						element
							.comment
							.first()
							.expect("an interstitial has exactly one comment"),
					);
					crowded = true;
				}
			}
		}

		if separate_token && crowded {
			self.write(" ");
		}
	}

	/// Go's `fill`.
	pub fn fill(&mut self, fodder: &Fodder, crowded: bool, separate_token: bool) {
		self.fodder_fill(fodder, crowded, separate_token, false);
	}

	/// Go's `fillFinal`, for the fodder after the last token of a file.
	pub fn fill_final(&mut self, fodder: &Fodder, crowded: bool, separate_token: bool) {
		self.fodder_fill(fodder, crowded, separate_token, true);
	}

	/// Render the trailing fodder of a file and guarantee the final newline.
	///
	/// This is the tail of `FormatNode`. Final whitespace is stripped at lex
	/// time, so an empty trailing fodder — or one ending in an interstitial,
	/// which emits no newline of its own — would otherwise leave the file
	/// without one.
	pub fn finish_file(&mut self, final_fodder: &Fodder) {
		self.fill_final(final_fodder, true, false);
		let needs_newline = final_fodder
			.last()
			.is_none_or(|last| last.kind == FodderKind::Interstitial);
		if needs_newline {
			self.write("\n");
		}
	}

	/// The accumulated output.
	pub fn finish(self) -> String {
		self.buf
	}

	// -----------------------------------------------------------------------
	// The AST walk. Go's `unparse` and its helpers.
	// -----------------------------------------------------------------------

	/// Go's `unparseSpecs`.
	///
	/// Recurses into [`ForSpec::outer`] first, which is what puts the `for`
	/// clauses back in source order — the tree nests them the other way round.
	fn unparse_specs(&mut self, spec: &ForSpec) {
		if let Some(outer) = &spec.outer {
			self.unparse_specs(outer);
		}
		self.fill(&spec.for_fodder, true, true);
		self.write("for");
		self.fill(&spec.var_fodder, true, true);
		self.write(&spec.var_name);
		self.fill(&spec.in_fodder, true, true);
		self.write("in");
		self.unparse(&spec.expr, true);
		for condition in &spec.conditions {
			self.fill(&condition.if_fodder, true, true);
			self.write("if");
			self.unparse(&condition.expr, true);
		}
	}

	/// Go's `unparseParams`.
	fn unparse_params(
		&mut self,
		fodder_left: &Fodder,
		params: &[Parameter],
		trailing_comma: bool,
		fodder_right: &Fodder,
	) {
		self.fill(fodder_left, false, false);
		self.write("(");
		let mut first = true;
		for param in params {
			if !first {
				self.write(",");
			}
			self.fill(&param.name_fodder, !first, true);
			self.write(&param.name);
			if let Some(default_arg) = &param.default_arg {
				self.fill(&param.eq_fodder, false, false);
				self.write("=");
				self.unparse(default_arg, false);
			}
			self.fill(&param.comma_fodder, false, false);
			first = false;
		}
		if trailing_comma {
			self.write(",");
		}
		self.fill(fodder_right, false, false);
		self.write(")");
	}

	/// Go's `unparseFieldParams`.
	fn unparse_field_params(&mut self, method: Option<&FunctionSugar>) {
		if let Some(method) = method {
			self.unparse_params(
				&method.paren_left_fodder,
				&method.parameters,
				method.trailing_comma,
				&method.paren_right_fodder,
			);
		}
	}

	/// The tail of a basic field: the method's parens, the `:`, and the value.
	/// Go's `unparseFieldRemainder` closure.
	fn unparse_field_remainder(&mut self, field: &ObjectField) {
		self.unparse_field_params(field.method.as_ref());
		self.fill(&field.op_fodder, false, false);
		if field.super_sugar {
			self.write("+");
		}
		self.write(match field.hide {
			ObjectFieldHide::Inherit => ":",
			ObjectFieldHide::Hidden => "::",
			ObjectFieldHide::Visible => ":::",
		});
		if let Some(expr2) = &field.expr2 {
			self.unparse(expr2, true);
		}
	}

	/// Go's `unparseFields`.
	///
	/// `crowded` is `PadObjects` for an object and `true` for a comprehension,
	/// and only affects the first field.
	fn unparse_fields(&mut self, fields: &[ObjectField], crowded: bool) {
		let mut first = true;
		for field in fields {
			if !first {
				self.write(",");
			}

			match field.kind {
				ObjectFieldKind::Local => {
					self.fill(&field.fodder1, !first || crowded, true);
					self.write("local");
					self.fill(&field.fodder2, true, true);
					if let Some(id) = &field.id {
						self.write(id);
					}
					self.unparse_field_params(field.method.as_ref());
					self.fill(&field.op_fodder, true, true);
					self.write("=");
					if let Some(expr2) = &field.expr2 {
						self.unparse(expr2, true);
					}
				}

				ObjectFieldKind::FieldId => {
					self.fill(&field.fodder1, !first || crowded, true);
					if let Some(id) = &field.id {
						self.write(id);
					}
					self.unparse_field_remainder(field);
				}

				ObjectFieldKind::FieldStr => {
					// No `fodder1`: the name is an expression and carries its
					// own opening fodder.
					if let Some(expr1) = &field.expr1 {
						self.unparse(expr1, !first || crowded);
					}
					self.unparse_field_remainder(field);
				}

				ObjectFieldKind::FieldExpr => {
					self.fill(&field.fodder1, !first || crowded, true);
					self.write("[");
					if let Some(expr1) = &field.expr1 {
						self.unparse(expr1, false);
					}
					self.fill(&field.fodder2, false, false);
					self.write("]");
					self.unparse_field_remainder(field);
				}

				ObjectFieldKind::Assert => {
					self.fill(&field.fodder1, !first || crowded, true);
					self.write("assert");
					if let Some(expr2) = &field.expr2 {
						self.unparse(expr2, true);
					}
					if let Some(expr3) = &field.expr3 {
						self.fill(&field.op_fodder, true, true);
						self.write(":");
						self.unparse(expr3, true);
					}
				}
			}

			first = false;
			self.fill(&field.comma_fodder, false, false);
		}
	}

	/// Go's `unparse`.
	///
	/// `crowded` says whether what was printed last would run into this node's
	/// first token. The opening fodder is filled here **only for a node that is
	/// not left-recursive**: where it is, the fodder lives further down the
	/// tree and the recursive call on the left child fills it instead.
	#[allow(clippy::too_many_lines)]
	pub fn unparse(&mut self, node: &Node, crowded: bool) {
		if node.left_recursive().is_none() {
			self.fill(&node.fodder, crowded, true);
		}

		match &node.kind {
			NodeKind::Apply(apply) => {
				self.unparse(&apply.target, crowded);
				self.fill(&apply.fodder_left, false, false);
				self.write("(");
				let mut first = true;
				for arg in &apply.arguments.positional {
					if !first {
						self.write(",");
					}
					self.unparse(&arg.expr, !first);
					self.fill(&arg.comma_fodder, false, false);
					first = false;
				}
				for arg in &apply.arguments.named {
					if !first {
						self.write(",");
					}
					self.fill(&arg.name_fodder, !first, true);
					self.write(&arg.name);
					// `eq_fodder` is deliberately not filled: upstream writes
					// the `=` directly, so a comment there is dropped.
					self.write("=");
					self.unparse(&arg.arg, false);
					self.fill(&arg.comma_fodder, false, false);
					first = false;
				}
				if apply.trailing_comma {
					self.write(",");
				}
				self.fill(&apply.fodder_right, false, false);
				self.write(")");
				if apply.tail_strict {
					self.fill(&apply.tail_strict_fodder, true, true);
					self.write("tailstrict");
				}
			}

			NodeKind::ApplyBrace(brace) => {
				self.unparse(&brace.left, crowded);
				self.unparse(&brace.right, true);
			}

			NodeKind::Array(array) => {
				self.write("[");
				let mut first = true;
				for element in &array.elements {
					if !first {
						self.write(",");
					}
					self.unparse(&element.expr, !first || self.options.pad_arrays);
					self.fill(&element.comma_fodder, false, false);
					first = false;
				}
				if array.trailing_comma {
					self.write(",");
				}
				let crowded = !array.elements.is_empty();
				self.fill(&array.close_fodder, crowded, self.options.pad_arrays);
				self.write("]");
			}

			NodeKind::ArrayComp(comp) => {
				self.write("[");
				self.unparse(&comp.body, self.options.pad_arrays);
				self.fill(&comp.trailing_comma_fodder, false, false);
				if comp.trailing_comma {
					self.write(",");
				}
				self.unparse_specs(&comp.spec);
				self.fill(&comp.close_fodder, true, self.options.pad_arrays);
				self.write("]");
			}

			NodeKind::Assert(assert) => {
				self.write("assert");
				self.unparse(&assert.cond, true);
				if let Some(message) = &assert.message {
					self.fill(&assert.colon_fodder, true, true);
					self.write(":");
					self.unparse(message, true);
				}
				self.fill(&assert.semicolon_fodder, false, false);
				self.write(";");
				self.unparse(&assert.rest, true);
			}

			NodeKind::Binary(binary) => {
				self.unparse(&binary.left, crowded);
				self.fill(&binary.op_fodder, true, true);
				self.write(binary.op.as_str());
				self.unparse(&binary.right, true);
			}

			NodeKind::Conditional(conditional) => {
				self.write("if");
				self.unparse(&conditional.cond, true);
				self.fill(&conditional.then_fodder, true, true);
				self.write("then");
				self.unparse(&conditional.branch_true, true);
				if let Some(branch_false) = &conditional.branch_false {
					self.fill(&conditional.else_fodder, true, true);
					self.write("else");
					self.unparse(branch_false, true);
				}
			}

			NodeKind::Dollar => self.write("$"),

			NodeKind::Error(error) => {
				self.write("error");
				self.unparse(&error.expr, true);
			}

			NodeKind::Function(function) => {
				self.write("function");
				self.unparse_params(
					&function.paren_left_fodder,
					&function.parameters,
					function.trailing_comma,
					&function.paren_right_fodder,
				);
				self.unparse(&function.body, true);
			}

			NodeKind::Import(import) => {
				self.write("import");
				self.unparse(&import.file, true);
			}
			NodeKind::ImportStr(import) => {
				self.write("importstr");
				self.unparse(&import.file, true);
			}
			NodeKind::ImportBin(import) => {
				self.write("importbin");
				self.unparse(&import.file, true);
			}

			NodeKind::Index(index) => {
				self.unparse(&index.target, crowded);
				// Also the dot fodder, when an id is used.
				self.fill(&index.left_bracket_fodder, false, false);
				if let Some(id) = &index.id {
					self.write(".");
					// Doubling as the id fodder.
					self.fill(&index.right_bracket_fodder, false, false);
					self.write(id);
				} else {
					self.write("[");
					if let Some(inner) = &index.index {
						self.unparse(inner, false);
					}
					self.fill(&index.right_bracket_fodder, false, false);
					self.write("]");
				}
			}

			NodeKind::Slice(slice) => {
				self.unparse(&slice.target, crowded);
				self.fill(&slice.left_bracket_fodder, false, false);
				self.write("[");
				if let Some(begin) = &slice.begin_index {
					self.unparse(begin, false);
				}
				self.fill(&slice.end_colon_fodder, false, false);
				self.write(":");
				if let Some(end) = &slice.end_index {
					self.unparse(end, false);
				}
				// The step colon is written when there is a step *or* when
				// this slot holds fodder — which is the whole reason its
				// emptiness is meaningful.
				if slice.step.is_some() || !slice.step_colon_fodder.is_empty() {
					self.fill(&slice.step_colon_fodder, false, false);
					self.write(":");
					if let Some(step) = &slice.step {
						self.unparse(step, false);
					}
				}
				self.fill(&slice.right_bracket_fodder, false, false);
				self.write("]");
			}

			NodeKind::InSuper(in_super) => {
				self.unparse(&in_super.index, true);
				self.fill(&in_super.in_fodder, true, true);
				self.write("in");
				self.fill(&in_super.super_fodder, true, true);
				self.write("super");
			}

			NodeKind::Local(local) => {
				self.write("local");
				assert!(
					!local.binds.is_empty(),
					"INTERNAL ERROR: local with no binds"
				);
				let mut first = true;
				for bind in &local.binds {
					if !first {
						self.write(",");
					}
					first = false;
					self.fill(&bind.var_fodder, true, true);
					self.write(&bind.variable);
					if let Some(fun) = &bind.fun {
						self.unparse_params(
							&fun.paren_left_fodder,
							&fun.parameters,
							fun.trailing_comma,
							&fun.paren_right_fodder,
						);
					}
					self.fill(&bind.eq_fodder, true, true);
					self.write("=");
					self.unparse(&bind.body, true);
					self.fill(&bind.close_fodder, false, false);
				}
				self.write(";");
				self.unparse(&local.body, true);
			}

			NodeKind::LiteralBoolean(value) => {
				self.write(if *value { "true" } else { "false" });
			}

			NodeKind::LiteralNumber(number) => self.write(&number.original_string),

			NodeKind::LiteralString(literal) => self.write_literal_string(literal),

			NodeKind::LiteralNull => self.write("null"),

			NodeKind::Object(object) => {
				self.write("{");
				self.unparse_fields(&object.fields, self.options.pad_objects);
				if object.trailing_comma {
					self.write(",");
				}
				let crowded = !object.fields.is_empty();
				self.fill(&object.close_fodder, crowded, self.options.pad_objects);
				self.write("}");
			}

			NodeKind::ObjectComp(comp) => {
				self.write("{");
				self.unparse_fields(&comp.fields, self.options.pad_objects);
				if comp.trailing_comma {
					self.write(",");
				}
				self.unparse_specs(&comp.spec);
				self.fill(&comp.close_fodder, true, self.options.pad_objects);
				self.write("}");
			}

			NodeKind::Parens(parens) => {
				self.write("(");
				self.unparse(&parens.inner, false);
				self.fill(&parens.close_fodder, false, false);
				self.write(")");
			}

			NodeKind::SelfExpr => self.write("self"),

			NodeKind::SuperIndex(super_index) => {
				self.write("super");
				self.fill(&super_index.dot_fodder, false, false);
				if let Some(id) = &super_index.id {
					self.write(".");
					self.fill(&super_index.id_fodder, false, false);
					self.write(id);
				} else {
					self.write("[");
					if let Some(inner) = &super_index.index {
						self.unparse(inner, false);
					}
					self.fill(&super_index.id_fodder, false, false);
					self.write("]");
				}
			}

			NodeKind::Var(id) => self.write(id),

			NodeKind::Unary(unary) => {
				self.write(unary.op.as_str());
				self.unparse(&unary.expr, false);
			}
		}
	}

	/// The five string kinds, each written back the way it came in.
	///
	/// A fully escaped kind still carries its source escapes, so it is written
	/// verbatim; a verbatim kind was unescaped by the parser, so its doubled
	/// quotes go back in here.
	fn write_literal_string(&mut self, literal: &LiteralString) {
		match literal.kind {
			LiteralStringKind::Double => {
				self.write("\"");
				self.write(&literal.value);
				self.write("\"");
			}
			LiteralStringKind::Single => {
				self.write("'");
				self.write(&literal.value);
				self.write("'");
			}
			LiteralStringKind::Block => self.write_block_string(literal),
			LiteralStringKind::VerbatimDouble => {
				self.write("@\"");
				self.write(&literal.value.replace('"', "\"\""));
				self.write("\"");
			}
			LiteralStringKind::VerbatimSingle => {
				self.write("@'");
				self.write(&literal.value.replace('\'', "''"));
				self.write("'");
			}
		}
	}

	/// A `|||` block string.
	///
	/// Two details are upstream's and both are visible in the output: `\r` is
	/// dropped outright — "Formatter always outputs in unix mode" — and a value
	/// not ending in a newline is written with the `|||-` chomping marker.
	fn write_block_string(&mut self, literal: &LiteralString) {
		let value = &literal.value;
		let ends_with_newline = value.ends_with('\n');

		self.write("|||");
		if !ends_with_newline {
			self.write("-");
		}
		self.write("\n");
		if !value.starts_with('\n') {
			self.write(&literal.block_indent);
		}

		// Go indexes the *next byte* while iterating runes, so the indent goes
		// in after a newline unless the next character is another newline —
		// a blank line is left unindented.
		let bytes = value.as_bytes();
		for (index, c) in value.char_indices() {
			if c == '\r' {
				continue;
			}
			self.buf.push(c);
			let next = index + c.len_utf8();
			if c == '\n' && next < bytes.len() && bytes[next] != b'\n' {
				self.write(&literal.block_indent);
			}
		}

		if !ends_with_newline {
			self.write("\n");
		}
		self.write(&literal.block_term_indent);
		self.write("|||");
	}
}

#[cfg(test)]
mod tests {
	use super::*;
	use crate::fodder::FodderElement;

	fn render(fodder: &Fodder, crowded: bool, separate_token: bool, is_final: bool) -> String {
		let mut unparser = Unparser::new(Options::default());
		unparser.fodder_fill(fodder, crowded, separate_token, is_final);
		unparser.finish()
	}

	fn interstitial(text: &str) -> FodderElement {
		FodderElement::new(FodderKind::Interstitial, 0, 0, vec![text.to_owned()])
	}

	fn fodder_of(elements: Vec<FodderElement>) -> Fodder {
		Fodder::from_elements(elements)
	}

	#[test]
	fn empty_fodder_separates_two_crowded_tokens() {
		// The whole point of `separate_token`: nothing to render, but the
		// tokens either side would run together.
		assert_eq!(render(&Fodder::new(), true, true, false), " ");
		assert_eq!(render(&Fodder::new(), true, false, false), "");
		assert_eq!(render(&Fodder::new(), false, true, false), "");
		assert_eq!(render(&Fodder::new(), false, false, false), "");
	}

	#[test]
	fn a_newline_ending_cancels_the_separating_space() {
		// A line end sets `crowded` false, so no trailing space is added even
		// though the caller asked to separate.
		let fodder = fodder_of(vec![FodderElement::line_end(0, 0)]);
		assert_eq!(render(&fodder, true, true, false), "\n");
	}

	#[test]
	fn an_interstitial_takes_a_leading_space_only_when_crowded() {
		let fodder = fodder_of(vec![interstitial("/* x */")]);
		assert_eq!(render(&fodder, true, false, false), " /* x */");
		assert_eq!(render(&fodder, false, false, false), "/* x */");
	}

	#[test]
	fn an_interstitial_ending_creates_a_crowd_that_was_not_there() {
		// `crowded` was false going in, but the interstitial leaves the output
		// crowded, so `separate_token` now has something to do.
		let fodder = fodder_of(vec![interstitial("/* x */")]);
		assert_eq!(render(&fodder, false, true, false), "/* x */ ");
	}

	#[test]
	fn a_line_end_comment_always_gets_exactly_two_spaces() {
		// Whatever the author wrote. This single behaviour is why the round
		// trip cannot be the identity.
		let fodder = fodder_of(vec![FodderElement::new(
			FodderKind::LineEnd,
			0,
			0,
			vec!["// hi".to_owned()],
		)]);
		assert_eq!(render(&fodder, false, false, false), "  // hi\n");
	}

	#[test]
	fn blanks_and_indent_follow_the_newline() {
		let fodder = fodder_of(vec![FodderElement::line_end(2, 4)]);
		assert_eq!(render(&fodder, false, false, false), "\n\n\n    ");
	}

	#[test]
	fn the_final_element_emits_no_blanks_or_indent() {
		let fodder = fodder_of(vec![FodderElement::line_end(2, 4)]);
		assert_eq!(render(&fodder, false, false, true), "\n");
	}

	#[test]
	fn only_the_last_element_is_treated_as_final() {
		// A line end, an interstitial after it, then another line end — which
		// is a shape `Fodder::append` will actually build, since a line end
		// following an interstitial is appended rather than merged.
		let fodder = fodder_of(vec![
			FodderElement::line_end(1, 2),
			interstitial("/* x */"),
			FodderElement::line_end(1, 2),
		]);
		// The first still renders its blank line and its indent; only the last
		// one is trimmed.
		assert_eq!(render(&fodder, false, false, true), "\n\n  /* x */\n");
	}

	#[test]
	fn paragraph_continuation_lines_use_the_previous_indent() {
		// `last_indent` comes from the element *before* the paragraph, not from
		// the paragraph itself — the first line was already indented by that
		// previous element.
		let fodder = fodder_of(vec![
			FodderElement::line_end(0, 2),
			FodderElement::new(
				FodderKind::Paragraph,
				0,
				6,
				vec!["/* a".to_owned(), " b */".to_owned()],
			),
		]);
		assert_eq!(
			render(&fodder, false, false, false),
			"\n  /* a\n   b */\n      "
		);
	}

	#[test]
	fn an_empty_paragraph_line_is_not_indented() {
		let fodder = fodder_of(vec![
			FodderElement::line_end(0, 2),
			FodderElement::new(
				FodderKind::Paragraph,
				0,
				0,
				vec!["/* a".to_owned(), String::new(), "b */".to_owned()],
			),
		]);
		assert_eq!(render(&fodder, false, false, false), "\n  /* a\n\n  b */\n");
	}

	#[test]
	fn finish_file_adds_the_newline_the_lexer_stripped() {
		let mut unparser = Unparser::new(Options::default());
		unparser.write("x");
		unparser.finish_file(&Fodder::new());
		assert_eq!(unparser.finish(), "x\n");
	}

	#[test]
	fn finish_file_adds_a_newline_after_a_trailing_interstitial() {
		let mut unparser = Unparser::new(Options::default());
		unparser.write("x");
		unparser.finish_file(&fodder_of(vec![interstitial("/* end */")]));
		assert_eq!(unparser.finish(), "x /* end */\n");
	}

	#[test]
	fn finish_file_does_not_double_the_newline_after_a_line_end() {
		let mut unparser = Unparser::new(Options::default());
		unparser.write("x");
		unparser.finish_file(&fodder_of(vec![FodderElement::line_end(3, 0)]));
		// `fill_final` emits the newline and drops the blanks, and the file
		// already ends cleanly, so nothing more is added.
		assert_eq!(unparser.finish(), "x\n");
	}
}
