.PHONY: target/release/jrsonnet target/release/rtk target/release/tk-compare build-rtk-quiet build-tk-compare-quiet tk-compare-grafana lint lint-all lint-ci fmt fmt-check test test-rtk check check-rtk ci ci-full help update-golden-fixtures check-golden-fixtures update-glob-truth-table check-glob-truth-table update-fmt-corpus check-fmt-corpus update-fmt-lexer-oracle update-fmt-node-oracle update-fmt-pass-oracle

.DEFAULT_GOAL := help

help:
	@echo "Available targets:"
	@echo "  build-rtk              - Build the rtk binary in release mode"
	@echo "  build-tk-compare       - Build the tk-compare binary in release mode"
	@echo "  lint                   - Run clippy linter on rtk"
	@echo "  lint-all               - Run clippy linter on all packages"
	@echo "  lint-ci                - Run clippy with CI settings (-D warnings)"
	@echo "  fmt                    - Format code with rustfmt"
	@echo "  fmt-check              - Check code formatting (no changes)"
	@echo "  test                   - Run all tests"
	@echo "  test-rtk               - Run rtk tests only"
	@echo "  check                  - Run all checks (fmt-check, lint, test)"
	@echo "  check-rtk              - Run rtk checks only (fmt-check, lint, test-rtk)"
	@echo "  ci                     - Run CI checks locally (fmt, lint-ci, test-rtk)"
	@echo "  ci-full                - Run full CI checks (fmt, lint-ci, all tests)"
	@echo "  update-golden-fixtures - Regenerate golden files in test_fixtures using tk export"
	@echo "  check-golden-fixtures  - Check that golden files are up to date (requires tk)"
	@echo "  update-glob-truth-table - Regenerate the gobwas/glob truth table (requires Go)"
	@echo "  check-glob-truth-table - Check the gobwas/glob truth table is up to date (requires Go)"
	@echo "  update-fmt-corpus      - Regenerate the go-jsonnet formatter corpus (requires Go)"
	@echo "  check-fmt-corpus       - Check the formatter corpus is up to date (requires Go)"
	@echo "  update-fmt-lexer-oracle - Regenerate the go-jsonnet token/fodder oracle (requires Go)"
	@echo "  update-fmt-node-oracle - Regenerate the go-jsonnet AST/fodder-slot oracle (requires Go)"
	@echo "  update-fmt-pass-oracle - Regenerate the go-jsonnet per-pass AST oracle (requires Go)"

target/release/jrsonnet:
	@cargo build --release -p jrsonnet

target/release/rtk:
	@cargo build --release -p rtk

target/release/tk-compare:
	@cargo build --release -p tk-compare

tk-compare: target/release/rtk target/release/tk-compare
	@target/release/tk-compare -- run tk-compare-grafana.toml --jrsonnet-path=target/release/jrsonnet --rtk=target/release/rtk

lint:
	@cargo clippy -p rtk --all-targets

lint-all:
	@cargo clippy --all-targets --all-features

fmt:
	@cargo fmt --all

fmt-check:
	@cargo fmt --all -- --check

test:
	@cargo test --all

test-rtk:
	@cargo test -p rtk

check: fmt-check lint test
	@echo "All checks passed!"

check-rtk: fmt-check lint test-rtk
	@echo "All rtk checks passed!"

# CI targets - match GitHub Actions settings
lint-ci:
	RUSTFLAGS="-D warnings" cargo clippy --all-targets

ci: fmt-check lint-ci test-rtk
	@echo "All CI checks passed!"

ci-full: fmt-check lint-ci test
	@echo "All CI checks passed (full)!"

# Generate golden files for test_fixtures using tk export
# Uses .golden extension to prevent accidental reformatting
GOLDEN_FIXTURES_DIR := test_fixtures/golden_envs

update-golden-fixtures: target/release/jrsonnet target/release/tk-compare
	@echo "Generating golden files for $(GOLDEN_FIXTURES_DIR)..."
	@target/release/tk-compare --jrsonnet-path $(CURDIR)/target/release/jrsonnet golden-fixtures --fixtures-dir $(GOLDEN_FIXTURES_DIR)

# Check that golden files are up to date (for CI)
check-golden-fixtures: target/release/jrsonnet target/release/tk-compare
	@echo "Checking golden files are up to date..."
	@target/release/tk-compare --jrsonnet-path $(CURDIR)/target/release/jrsonnet golden-fixtures --dry-run --fixtures-dir $(GOLDEN_FIXTURES_DIR)
	@echo "Golden files are up to date."

# The oracle rtk-gobwas-glob is graded against, generated by the exact library
# and version tk links. Read the table, not gobwas' documentation: the two
# disagree about separators, and it is the table that decides which files
# `rtk fmt` and `rtk lint` touch.
GLOB_GENERATE_DIR := crates/rtk-gobwas-glob/testdata/generate
GLOB_TRUTH_TABLE := crates/rtk-gobwas-glob/testdata/gobwas-glob-v0.2.3.json

update-glob-truth-table:
	@echo "Regenerating $(GLOB_TRUTH_TABLE) with gobwas/glob..."
	@cd $(GLOB_GENERATE_DIR) && go mod tidy && go run . > $(CURDIR)/$(GLOB_TRUTH_TABLE)
	@echo "Truth table regenerated. Review the diff before committing."

# The breadth corpus Phase 2 is measured against: go-jsonnet's formatter run
# over every Jsonnet file in this repository. Replaces the round-trip gate the
# plan originally asked for, which go-jsonnet itself does not satisfy — its
# unparser renders from the fodder model rather than copying the source.
FMT_GENERATE_DIR := crates/rtk-jsonnetfmt/testdata/generate
FMT_CORPUS_DIR := crates/rtk-jsonnetfmt/testdata/corpus

update-fmt-corpus:
	@echo "Regenerating $(FMT_CORPUS_DIR) with go-jsonnet's formatter..."
	@cd $(FMT_GENERATE_DIR) && go mod tidy && go run . $(CURDIR) $(CURDIR)/$(FMT_CORPUS_DIR)
	@echo "Corpus regenerated. Review the diff, and update matching= in"
	@echo "crates/rtk-jsonnetfmt/testdata/corpus-baseline.toml if the count moved."

check-fmt-corpus:
	@test -f $(FMT_CORPUS_DIR)/manifest.json || { \
		echo "$(FMT_CORPUS_DIR) is missing; run 'make update-fmt-corpus' (requires Go)"; \
		exit 1; \
	}
	@tmp=$$(mktemp -d) && \
		(cd $(FMT_GENERATE_DIR) && go mod tidy && go run . $(CURDIR) $$tmp) && \
		diff -ru $(FMT_CORPUS_DIR) $$tmp && rm -rf $$tmp
	@echo "Corpus is up to date."

# The lexer oracle: the tokens and fodder go-jsonnet's own lexer produces.
#
# Fodder is only observable from inside go-jsonnet — `internal/parser` is an
# internal package and `token`'s fields are unexported — so this stages a
# _test.go into a checkout and runs it there. Set GO_JSONNET_FOR_TESTS to an
# existing checkout (the nix devShell already does) or this clones the pinned
# version. Worth the staging: everything downstream of the lexer inherits its
# mistakes, and the corpus only sees them once they have reached text.
FMT_LEXER_ORACLE := crates/rtk-jsonnetfmt/testdata/lexer-oracle.json
# Snippets cover what the corpus cannot reach: it holds no verbatim string and
# provokes no lexer error, so without these the error messages would be pinned
# by expectations derived by hand rather than taken from go-jsonnet.
FMT_LEXER_SNIPPETS := crates/rtk-jsonnetfmt/testdata/lexer-snippets.json
FMT_LEXER_SNIPPET_ORACLE := crates/rtk-jsonnetfmt/testdata/lexer-snippet-oracle.json
GO_JSONNET_VERSION := v0.22.0

update-fmt-lexer-oracle:
	@test -f $(FMT_CORPUS_DIR)/manifest.json || { \
		echo "generate the corpus first: make update-fmt-corpus"; exit 1; \
	}
	@set -e; \
	checkout="$${GO_JSONNET_FOR_TESTS:-}"; \
	staged=""; \
	if [ -z "$$checkout" ]; then \
		staged=$$(mktemp -d); \
		echo "cloning go-jsonnet $(GO_JSONNET_VERSION) into $$staged..."; \
		git clone --quiet --depth 1 --branch $(GO_JSONNET_VERSION) \
			https://github.com/google/go-jsonnet "$$staged/go-jsonnet"; \
		checkout="$$staged/go-jsonnet"; \
	else \
		echo "using GO_JSONNET_FOR_TESTS at $$checkout"; \
		staged=$$(mktemp -d); \
		cp -R "$$checkout" "$$staged/go-jsonnet"; \
		chmod -R u+w "$$staged/go-jsonnet"; \
		checkout="$$staged/go-jsonnet"; \
	fi; \
	cp $(FMT_GENERATE_DIR)/fodderdump/fodderdump_test.go \
		"$$checkout/internal/parser/fodderdump_test.go"; \
	python3 -c "import json,sys; \
		m=json.load(open('$(FMT_CORPUS_DIR)/manifest.json')); \
		sys.stdout.write(''.join(e['source']+chr(10) for e in m['entries']))" \
		> "$$staged/sources.txt"; \
	( cd "$$checkout" && \
		FODDERDUMP_ROOT=$(CURDIR) \
		FODDERDUMP_SOURCES="$$staged/sources.txt" \
		FODDERDUMP_OUT=$(CURDIR)/$(FMT_LEXER_ORACLE) \
		go test -count=1 -run TestDumpFodder ./internal/parser ); \
	( cd "$$checkout" && \
		FODDERDUMP_SNIPPETS=$(CURDIR)/$(FMT_LEXER_SNIPPETS) \
		FODDERDUMP_OUT=$(CURDIR)/$(FMT_LEXER_SNIPPET_ORACLE) \
		go test -count=1 -run TestDumpFodder ./internal/parser ); \
	rm -rf "$$staged"
	@echo "Wrote $(FMT_LEXER_ORACLE) and $(FMT_LEXER_SNIPPET_ORACLE)."

# The node oracle: the AST go-jsonnet's parser produces, with every named
# fodder slot of every node.
#
# The parser is written against this rather than against a reading of Go's
# source, for the reason the lexer was: of 16 lexer expectations derived by
# reading, 2 were wrong, and both were about fodder the model *composes* rather
# than reads. A parser composes fodder at nearly every node. The text-level
# corpus cannot locate one of those — a misplaced CommaFodder surfaces as a
# whitespace diff hundreds of lines away — and this names the slot.
#
# Unlike the lexer oracle this needs no staged checkout and no clone: every
# fodder slot is an exported field of package `ast`, and
# `formatter.SnippetToRawAST` is the same public entry point `Format` calls. So
# it is an ordinary program in the generate module, pinned to the same
# go-jsonnet the corpus came from.
FMT_NODE_ORACLE := crates/rtk-jsonnetfmt/testdata/node-oracle.json
# Snippets cover what the corpus cannot: it holds no `@"..."` at all, and one
# file each with tailstrict or importbin, so those slots would otherwise be
# graded by nothing.
FMT_NODE_SNIPPETS := crates/rtk-jsonnetfmt/testdata/node-snippets.json
FMT_NODE_SNIPPET_ORACLE := crates/rtk-jsonnetfmt/testdata/node-snippet-oracle.json

update-fmt-node-oracle:
	@test -f $(FMT_CORPUS_DIR)/manifest.json || { \
		echo "generate the corpus first: make update-fmt-corpus"; exit 1; \
	}
	@cd $(FMT_GENERATE_DIR) && go mod tidy && \
		go run ./nodedump files $(CURDIR) \
			$(CURDIR)/$(FMT_CORPUS_DIR)/manifest.json \
			$(CURDIR)/$(FMT_NODE_ORACLE)
	@cd $(FMT_GENERATE_DIR) && \
		go run ./nodedump snippets \
			$(CURDIR)/$(FMT_NODE_SNIPPETS) \
			$(CURDIR)/$(FMT_NODE_SNIPPET_ORACLE)
	@echo "Wrote $(FMT_NODE_ORACLE) and $(FMT_NODE_SNIPPET_ORACLE)."

# The pass oracle: the AST each formatter pass leaves behind.
#
# The node oracle grades the parser and the corpus grades the whole pipeline;
# between them sits the question this answers — what does one pass do? The
# corpus cannot answer it. Of the 138 files it holds, `PrettyFieldNames`
# changes two and `FixTrailingCommas` and `NoRedundantSliceColon` change
# **none**, because Jsonnet already formatted by `tk fmt` gives a pass nothing
# to do. Neither can `Options`: three passes have a flag, the rest are
# unconditional.
#
# So this one is staged, like the lexer oracle and for the same kind of reason.
# `internal/formatter` may only be imported from inside go-jsonnet's own
# module, so the dumper is copied into a checkout as `rtkpassdump/` and run
# there — a `package main` inside the module, which needs no `_test.go` trick.
# nodedump/dump.go goes with it, so both oracles speak one notation.
#
# Each pass runs on its own fresh parse rather than on the pipeline's
# accumulated state: that is what lets a pass be graded before the passes
# ahead of it in `FormatNode` exist, which is the whole point of landing them
# one at a time. See crates/rtk-jsonnetfmt/testdata/generate/_staged/passdump.go.
FMT_PASS_ORACLE := crates/rtk-jsonnetfmt/testdata/pass-oracle.json
# Snippets are where this oracle earns its keep: they are the only grading two
# of the three Phase 2b passes get at all.
FMT_PASS_SNIPPETS := crates/rtk-jsonnetfmt/testdata/pass-snippets.json
FMT_PASS_SNIPPET_ORACLE := crates/rtk-jsonnetfmt/testdata/pass-snippet-oracle.json

update-fmt-pass-oracle:
	@test -f $(FMT_CORPUS_DIR)/manifest.json || { \
		echo "generate the corpus first: make update-fmt-corpus"; exit 1; \
	}
	@set -e; \
	checkout="$${GO_JSONNET_FOR_TESTS:-}"; \
	staged=$$(mktemp -d); \
	if [ -z "$$checkout" ]; then \
		echo "cloning go-jsonnet $(GO_JSONNET_VERSION) into $$staged..."; \
		git clone --quiet --depth 1 --branch $(GO_JSONNET_VERSION) \
			https://github.com/google/go-jsonnet "$$staged/go-jsonnet"; \
	else \
		echo "using GO_JSONNET_FOR_TESTS at $$checkout"; \
		cp -R "$$checkout" "$$staged/go-jsonnet"; \
		chmod -R u+w "$$staged/go-jsonnet"; \
	fi; \
	checkout="$$staged/go-jsonnet"; \
	mkdir -p "$$checkout/rtkpassdump"; \
	cp $(FMT_GENERATE_DIR)/_staged/passdump.go \
		$(FMT_GENERATE_DIR)/nodedump/dump.go \
		"$$checkout/rtkpassdump/"; \
	( cd "$$checkout" && \
		go run ./rtkpassdump files $(CURDIR) \
			$(CURDIR)/$(FMT_CORPUS_DIR)/manifest.json \
			$(CURDIR)/$(FMT_PASS_ORACLE) ); \
	( cd "$$checkout" && \
		go run ./rtkpassdump snippets \
			$(CURDIR)/$(FMT_PASS_SNIPPETS) \
			$(CURDIR)/$(FMT_PASS_SNIPPET_ORACLE) ); \
	rm -rf "$$staged"
	@echo "Wrote $(FMT_PASS_ORACLE) and $(FMT_PASS_SNIPPET_ORACLE)."

check-glob-truth-table:
	@test -f $(GLOB_TRUTH_TABLE) || { \
		echo "$(GLOB_TRUTH_TABLE) is missing; run 'make update-glob-truth-table' (requires Go)"; \
		exit 1; \
	}
	@tmp=$$(mktemp) && \
		(cd $(GLOB_GENERATE_DIR) && go mod tidy && go run .) > $$tmp && \
		diff -u $(GLOB_TRUTH_TABLE) $$tmp && rm -f $$tmp
	@echo "Truth table is up to date."
