// Test manifestYamlFromJson -> parseYaml roundtrip
// This reproduces the issue where YAML generated by manifestYamlFromJson
// cannot be parsed back by parseYaml

local complexData = {
  // Basic types
  string: 'hello world',
  number: 42,
  float: 3.14,
  bool: true,
  'null': null,
  
  // Strings with special characters that might break YAML
  stringWithColon: 'key: value',
  stringWithQuotes: 'he said "hello"',
  stringWithApostrophe: "it's working",
  stringWithBrackets: '{key: value}',
  stringWithUrl: 'http://example.com:8080/path',
  stringWithMultiline: |||
    line 1
    line 2: value
    line 3
  |||,
  
  // Nested structures
  nested: {
    level1: {
      level2: {
        value: 'deep',
        array: [1, 2, 3],
      },
    },
  },
  
  // Arrays
  simpleArray: [1, 2, 3],
  objectArray: [
    { name: 'item1', value: 100 },
    { name: 'item2', value: 200 },
  ],
  mixedArray: [1, 'string', { key: 'value' }, [1, 2]],
  
  // Large numbers
  largeNumber: 1000000,
  scientificNotation: 1e6,
  
  // Keys with special characters
  'key-with-dashes': 'value',
  'key.with.dots': 'value',
  'key/with/slashes': 'value',
  
  // Values that look like YAML special cases
  stringTrue: 'true',
  stringFalse: 'false',
  stringNull: 'null',
  stringNumber: '123',
  stringFloat: '3.14',
  
  // Kubernetes-like structure (common in Tanka)
  aggregations_forwarding: {
    forwarding_enabled: true,
    ingestion_rate: 1000,
  },
  
  // Mimir-like limits structure
  limits: {
    max_global_series_per_user: 100000,
    ingestion_rate: 50000,
    'query-frontend': {
      'max-outstanding-per-tenant': 100,
    },
  },
};

local manifestYamlFromJson = std.native('manifestYamlFromJson');
local parseYaml = std.native('parseYaml');

// Step 1: Convert to JSON string
local jsonString = std.toString(complexData);

// Step 2: Convert JSON to YAML
local yamlString = manifestYamlFromJson(jsonString);

// Step 3: Try to parse YAML back
local parsed = parseYaml(yamlString);

{
  // Output the YAML for inspection
  yaml: yamlString,
  
  // Try to access the parsed data
  parsed: parsed,
  
  // Verify roundtrip
  success: true,
}

