//! Breadth: every Jsonnet file in this repository, formatted by go-jsonnet.
//!
//! This is what Phase 2 is measured against, and it replaces the round-trip
//! gate `docs/rtk-fmt-plan.md` originally asked for. That gate — `unparse(parse
//! (x)) == x` byte-for-byte — cannot hold, because go-jsonnet's unparser
//! renders text from the fodder model rather than copying the source: a tab
//! becomes eight spaces, a line-end comment is always preceded by exactly two
//! spaces, and `\r` is dropped from block strings. Asking rtk for a property
//! go-jsonnet itself lacks would have blocked the phase on a mistake.
//!
//! The goldens are produced by `testdata/generate`, which calls
//! `formatter.Format` directly — the identical call `tanka.Format` makes. So
//! matching them *is* matching `tk fmt`, with no `tk` binary in the loop and no
//! temporary paths baked into the answers.
//!
//! Comparison is by bytes. Trailing newline, tabs against spaces, CRLF and BOM
//! are exactly where a formatter port drifts, and a line-based comparison hides
//! all four.

use std::{fs, path::PathBuf};

use rtk_jsonnetfmt::{Options, coalesce_error, format};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Manifest {
	/// Which go-jsonnet produced these answers.
	go_jsonnet_version: String,
	entries: Vec<Entry>,
}

#[derive(Debug, Deserialize)]
struct Entry {
	/// Repository-relative, and also the diagnostic filename the generator
	/// passed to `Format` — so the Rust side has to pass the same one or the
	/// error goldens cannot match.
	source: String,
	golden: String,
	#[serde(default)]
	error: bool,
}

#[derive(Debug, Deserialize)]
struct Baseline {
	matching: usize,
}

fn crate_dir() -> PathBuf {
	PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn repo_root() -> PathBuf {
	crate_dir()
		.parent()
		.and_then(|crates| crates.parent())
		.expect("the crate is two levels below the repository root")
		.to_path_buf()
}

#[test]
fn corpus_matches_go_jsonnet_at_the_recorded_rate() {
	let corpus = crate_dir().join("testdata/corpus");
	let manifest_path = corpus.join("manifest.json");

	let Ok(raw) = fs::read_to_string(&manifest_path) else {
		eprintln!(
			"no formatter corpus at {}; generate it with `make update-fmt-corpus` (needs Go). \
			 Skipping.",
			manifest_path.display()
		);
		return;
	};

	let manifest: Manifest = serde_json::from_str(&raw).expect("the manifest is valid JSON");
	assert!(!manifest.entries.is_empty(), "the corpus is empty");

	let baseline_path = crate_dir().join("testdata/corpus-baseline.toml");
	let baseline: Baseline = toml::from_str(
		&fs::read_to_string(&baseline_path)
			.unwrap_or_else(|err| panic!("reading {}: {err}", baseline_path.display())),
	)
	.unwrap_or_else(|err| panic!("parsing {}: {err}", baseline_path.display()));

	let root = repo_root();
	let mut matching = 0;
	let mut differing: Vec<String> = Vec::new();
	let mut missing_sources: Vec<String> = Vec::new();

	for entry in &manifest.entries {
		let Ok(input) = fs::read_to_string(root.join(&entry.source)) else {
			// A source file named by the manifest but no longer in the tree:
			// the corpus needs regenerating, and silently skipping it would
			// let the match count drift.
			missing_sources.push(entry.source.clone());
			continue;
		};

		let golden = fs::read_to_string(corpus.join(&entry.golden))
			.unwrap_or_else(|err| panic!("reading golden for {}: {err}", entry.source));

		let actual = coalesce_error(format(&entry.source, &input, &Options::default()));
		if actual == golden {
			matching += 1;
		} else {
			let kind = if entry.error { " (parse error)" } else { "" };
			differing.push(format!("{}{kind}", entry.source));
		}
	}

	assert!(
		missing_sources.is_empty(),
		"{} source file(s) in the manifest no longer exist. Run `make update-fmt-corpus`:\n  {}",
		missing_sources.len(),
		missing_sources.join("\n  ")
	);

	let total = manifest.entries.len();
	if matching != baseline.matching {
		// Show a bounded sample: with an unfinished formatter nearly every file
		// differs, and a 145-line panic buries the number that matters.
		const SAMPLE: usize = 15;
		let mut sample = differing
			.iter()
			.take(SAMPLE)
			.cloned()
			.collect::<Vec<_>>()
			.join("\n  ");
		if let Some(elided) = differing.len().checked_sub(SAMPLE).filter(|n| *n > 0) {
			sample.push_str(&format!("\n  ...and {elided} more"));
		}

		panic!(
			"corpus match count is {matching} of {total}, but \
			 testdata/corpus-baseline.toml records {}.\n\
			 \n\
			 If {matching} is higher, that is progress: set `matching = {matching}` in the same \
			 commit.\n\
			 If it is lower, something regressed — look at these:\n  {sample}\n\
			 \n\
			 Corpus generated by go-jsonnet {}.",
			baseline.matching, manifest.go_jsonnet_version
		);
	}

	eprintln!(
		"fmt corpus: {matching} of {total} match go-jsonnet {}",
		manifest.go_jsonnet_version
	);
}

/// Formatting go-jsonnet's own answer has to return that answer unchanged.
///
/// `docs/rtk-fmt-plan.md` asks for this per step, and Phase 2d is the step to
/// ask it of: `FixIndentation` and `FixNewlines` are the two passes that could
/// plausibly fail to settle, and the plan's original reasoning still holds —
/// a port that needs a second run to converge has a bug in one of them, and
/// adding a convergence loop would paper over it.
///
/// The inputs are the **goldens**, not the sources, which is what makes this a
/// clean test of the property: a golden is by construction a fixed point of
/// go-jsonnet's own `Format`, so any movement here is rtk's.
///
/// # This is not an unconditional property
///
/// Phase 2c found that `jsonnetfmt` is not a fixed point in general —
/// `a['fo` `o` `']` formats to `a['foo']` and then to `a.foo`, because
/// `PrettyFieldNames` at step 10 sees the escape that `EnforceStringStyle`
/// removes at step 11. That is upstream's, and it is what `tk fmt` prints. So
/// a failure here is a bug **until** it is traced to a specific cross-pass
/// interaction in `FormatNode`'s order, at which point it is recorded in
/// `CLAUDE.md` and excluded by name. No corpus golden reaches the 2c case
/// today, so the list below is empty and the assertion is exact.
#[test]
fn formatting_a_golden_again_changes_nothing() {
	/// Goldens excluded because they hit a documented upstream
	/// non-convergence. Empty, and it may only grow with a `CLAUDE.md` entry.
	const KNOWN_NON_CONVERGENT: &[&str] = &[];

	let corpus = crate_dir().join("testdata/corpus");
	let manifest_path = corpus.join("manifest.json");

	let Ok(raw) = fs::read_to_string(&manifest_path) else {
		eprintln!(
			"no formatter corpus at {}; generate it with `make update-fmt-corpus` (needs Go). \
			 Skipping.",
			manifest_path.display()
		);
		return;
	};

	let manifest: Manifest = serde_json::from_str(&raw).expect("the manifest is valid JSON");

	let mut moved: Vec<String> = Vec::new();
	let mut checked = 0;

	for entry in &manifest.entries {
		// A golden holding a parse error is not Jsonnet; formatting it would
		// grade the error text, which `fixtures.rs` already does.
		if entry.error || KNOWN_NON_CONVERGENT.contains(&entry.source.as_str()) {
			continue;
		}

		let golden = fs::read_to_string(corpus.join(&entry.golden))
			.unwrap_or_else(|err| panic!("reading golden for {}: {err}", entry.source));

		let again = coalesce_error(format(&entry.source, &golden, &Options::default()));
		checked += 1;
		if again != golden {
			moved.push(entry.source.clone());
		}
	}

	assert!(
		moved.is_empty(),
		"{} golden(s) changed when formatted a second time. Each is a bug in a pass — most \
		 likely FixIndentation or FixNewlines — until it is traced to a specific cross-pass \
		 interaction in FormatNode's order. Do **not** add a convergence loop; see the \
		 correction in docs/rtk-fmt-plan.md, Phase 2.\n  {}",
		moved.len(),
		moved.join("\n  ")
	);

	eprintln!("fmt idempotence: {checked} goldens are fixed points");
}
