//! The red baseline: one harness, three fixture families, one ratchet.
//!
//! Phase 0 of the fmt port plan. Nothing here formats anything; it grades
//! whatever [`rtk_jsonnetfmt::format`] currently does against oracles that cost
//! nothing to trust:
//!
//! | family | what it grades | oracle |
//! | --- | --- | --- |
//! | `go_jsonnet/` | the pass pipeline, as a smoke test | go-jsonnet's own `formatter/testdata/*.fmt.golden` |
//! | `no_implicit_plus/` | `FixParens` and `*PlusObject` | upstream's inline `TestFormatNoImplicitPlus` cases |
//! | `parse_errors/` | the error text | messages derived from go-jsonnet's lexer and parser |
//!
//! The `go_jsonnet` goldens are free and authoritative: they are generated by
//! `Format(name, input, DefaultOptions())`, the identical call `tanka.Format`
//! makes. Matching them *is* matching `tk fmt`, with no `tk` binary and no
//! regeneration step.
//!
//! Everything is compared as **bytes**. Trailing newline, tabs against spaces,
//! CRLF and BOM are precisely where a formatter port drifts, and a line-based
//! comparison hides all four.

use std::{
	collections::{BTreeMap, BTreeSet},
	ffi::OsStr,
	fmt::Write as _,
	fs,
	path::{Path, PathBuf},
};

use rtk_jsonnetfmt::{Options, coalesce_error, format};
use serde::Deserialize;

/// One graded fixture.
struct Outcome {
	id: String,
	passed: bool,
	/// What to print when this one is unexpectedly red.
	detail: String,
}

impl Outcome {
	fn pass(id: String) -> Self {
		Self {
			id,
			passed: true,
			detail: String::new(),
		}
	}

	fn fail(id: String, expected: &str, actual: &str) -> Self {
		let detail = format!("\n  expected: {expected:?}\n  actual:   {actual:?}");
		Self {
			id,
			passed: false,
			detail,
		}
	}

	fn grade(id: String, expected: &str, actual: &str) -> Self {
		if expected == actual {
			Self::pass(id)
		} else {
			Self::fail(id, expected, actual)
		}
	}
}

#[derive(Debug, Deserialize)]
struct Quarantine {
	#[serde(default)]
	entry: Vec<QuarantineEntry>,
}

#[derive(Debug, Deserialize)]
struct QuarantineEntry {
	id: String,
	reason: String,
}

fn crate_dir() -> PathBuf {
	PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn load_quarantine() -> BTreeMap<String, String> {
	let path = crate_dir().join("quarantine.toml");
	let raw =
		fs::read_to_string(&path).unwrap_or_else(|err| panic!("reading {}: {err}", path.display()));
	let parsed: Quarantine =
		toml::from_str(&raw).unwrap_or_else(|err| panic!("parsing {}: {err}", path.display()));

	let mut by_id = BTreeMap::new();
	for entry in parsed.entry {
		assert!(
			!entry.reason.trim().is_empty(),
			"quarantine entry {:?} has no reason",
			entry.id
		);
		let previous = by_id.insert(entry.id.clone(), entry.reason);
		assert!(
			previous.is_none(),
			"quarantine entry {:?} is listed twice",
			entry.id
		);
	}
	by_id
}

/// The `.jsonnet` files in `dir`, sorted, so the report is stable.
fn jsonnet_files(dir: &Path) -> Vec<PathBuf> {
	let mut files: Vec<PathBuf> = fs::read_dir(dir)
		.unwrap_or_else(|err| panic!("reading {}: {err}", dir.display()))
		.map(|entry| entry.expect("directory entry is readable").path())
		.filter(|path| path.extension() == Some(OsStr::new("jsonnet")))
		.collect();
	files.sort();
	files
}

fn read(path: &Path) -> String {
	fs::read_to_string(path).unwrap_or_else(|err| panic!("reading {}: {err}", path.display()))
}

fn stem(path: &Path) -> String {
	path.file_stem()
		.expect("fixture has a stem")
		.to_string_lossy()
		.into_owned()
}

/// Upstream's `TestFormatNoImplicitPlus`, ported verbatim.
///
/// These are the only cases whose failure changes what a file *evaluates to*:
/// `{ a: 1 } { b: 2 }.a` has to become `({ a: 1 } + { b: 2 }).a`, and without
/// the injected parens the formatted expression is a runtime error rather than
/// a differently-spelled program.
///
/// They run with `use_implicit_plus` **off**, which exercises `AddPlusObject` —
/// the branch `DefaultOptions()` skips — so they are pass-level tests and not
/// end-to-end ones.
const NO_IMPLICIT_PLUS: [(&str, &str, &str); 9] = [
	(
		"implicit-plus-apply",
		"{ f(x):: x * x } { a: 1 }.f(99)\n",
		"({ f(x):: x * x } + { a: 1 }).f(99)\n",
	),
	(
		"implicit-plus-index",
		"{ a: 1 } { b: 2 }.a\n",
		"({ a: 1 } + { b: 2 }).a\n",
	),
	(
		"implicit-plus",
		"{ a: 1 } { b: 2 }\n",
		"{ a: 1 } + { b: 2 }\n",
	),
	(
		"implicit-plus-three",
		"{ a: 1 } { b: 2 } { c: 3 }\n",
		"{ a: 1 } + { b: 2 } + { c: 3 }\n",
	),
	(
		"implicit-plus-left",
		"{ a: 1 } + { b: 2 } { c: 3 }\n",
		"{ a: 1 } + ({ b: 2 } + { c: 3 })\n",
	),
	(
		"implicit-plus-right",
		"{ a: 1 } { b: 2 } + { c: 3 }\n",
		"{ a: 1 } + { b: 2 } + { c: 3 }\n",
	),
	(
		"implicit-plus-unary",
		"+ 42 { b: 2 }\n",
		"+(42 + { b: 2 })\n",
	),
	(
		"implicit-plus-mul-right",
		"{ a: 1 } * { b: 2 } { c: 3 }\n",
		"{ a: 1 } * ({ b: 2 } + { c: 3 })\n",
	),
	(
		"implicit-plus-mul-left",
		"{ a: 1 } { b: 2 } * { c: 3 }\n",
		"({ a: 1 } + { b: 2 }) * { c: 3 }\n",
	),
];

fn grade_no_implicit_plus(outcomes: &mut Vec<Outcome>) {
	let options = Options {
		use_implicit_plus: false,
		..Options::default()
	};

	for (name, input, golden) in NO_IMPLICIT_PLUS {
		let actual = coalesce_error(format(name, input, &options));
		outcomes.push(Outcome::grade(
			format!("no_implicit_plus/{name}"),
			golden,
			&actual,
		));
	}
}

fn grade_parse_errors(outcomes: &mut Vec<Outcome>) {
	let dir = crate_dir().join("tests/fixtures/parse_errors");
	let fixtures = jsonnet_files(&dir);
	assert!(
		!fixtures.is_empty(),
		"no parse-error fixtures in {}",
		dir.display()
	);

	for fixture in fixtures {
		let name = stem(&fixture);
		let input = read(&fixture);
		// The basename with its extension, never a path: the message embeds
		// whatever `DiagnosticFileName` it was handed, and a path would bake
		// the checkout location into the golden.
		let diagnostic_name = format!("{name}.jsonnet");
		let actual = coalesce_error(format(&diagnostic_name, &input, &Options::default()));

		let golden_path = dir.join(format!("{name}.err.golden"));
		let golden = read(&golden_path);
		// A go-jsonnet error message never ends in a newline, so stripping
		// exactly one is unambiguous and lets the goldens stay ordinary
		// newline-terminated text files.
		let golden = golden.strip_suffix('\n').unwrap_or(&golden);

		outcomes.push(Outcome::grade(
			format!("parse_errors/{name}"),
			golden,
			&actual,
		));
	}
}

/// Grade against go-jsonnet's own formatter goldens. Returns whether the family
/// was graded at all.
/// Where the `go_jsonnet/` fixtures come from: `GO_JSONNET_FOR_TESTS`, and
/// failing that a checkout at `target/go-jsonnet`.
///
/// The fallback is here rather than in the Makefile deliberately. It lived
/// there first, and that graded the family under `make test` while a plain
/// `cargo test -p rtk-jsonnetfmt` — which is what anyone actually runs while
/// working — still skipped it silently and printed `12 graded` rather than 15.
/// A skip that depends on the entry point is the same hazard as a skip that
/// depends on a missing file: the suite is green either way and says nothing.
///
/// # And that is exactly what it did, for three phases
///
/// This comment used to say the oracle targets leave a checkout at
/// `target/go-jsonnet`. **None of them did.** `update-fmt-node-oracle` is an
/// ordinary program in the generate module and takes go-jsonnet from the module
/// cache; `update-fmt-lexer-oracle` and `update-fmt-pass-oracle` clone into
/// `mktemp -d` and delete it. So outside the nix devShell — CI included — the
/// fallback resolved to nothing and this family graded 12 of 15, saying so only
/// in the eprintln below.
///
/// Which cost more than three fixtures. `go_jsonnet/empty_comment` is the only
/// end-to-end `EnforceCommentStyle` case in the suite, a pass that changes 0 of
/// the corpus files, and `go_jsonnet/regular_expression` is the only
/// authoritative answer for a parse error's doubled location and its range
/// shape. Phase 4 added `make go-jsonnet-checkout`, which is what makes the
/// sentence above true, and CI runs it as a side effect of checking the corpus.
fn go_jsonnet_checkout() -> Option<PathBuf> {
	if let Some(root) = std::env::var_os("GO_JSONNET_FOR_TESTS") {
		return Some(PathBuf::from(root));
	}
	let pinned = crate_dir()
		.parent()
		.and_then(Path::parent)
		.map(|root| root.join("target/go-jsonnet"))?;
	pinned.is_dir().then_some(pinned)
}

fn grade_go_jsonnet(outcomes: &mut Vec<Outcome>) -> bool {
	let Some(root) = go_jsonnet_checkout() else {
		eprintln!(
			"no go-jsonnet available for tests; run `make go-jsonnet-checkout`, which clones the \
			 pinned version to target/go-jsonnet, or set GO_JSONNET_FOR_TESTS to a checkout of \
			 your own — the `go_jsonnet/` fixtures are skipped without one, and two of the three \
			 carry answers nothing else in the suite has"
		);
		return false;
	};

	let dir = root.join("formatter/testdata");
	let fixtures = jsonnet_files(&dir);
	assert!(
		!fixtures.is_empty(),
		"a go-jsonnet checkout was found but {} holds no .jsonnet fixtures",
		dir.display()
	);

	for fixture in fixtures {
		let name = stem(&fixture);
		// Upstream skips escaped filenames.
		if name.contains('%') {
			continue;
		}

		let input = read(&fixture);
		// Upstream's test name is the match path with the extension stripped,
		// and it runs with the `formatter` directory as its working directory —
		// so `testdata/<stem>` is what reaches `DiagnosticFileName`, and what
		// any error golden was written against.
		let diagnostic_name = format!("testdata/{name}");
		let actual = coalesce_error(format(&diagnostic_name, &input, &Options::default()));

		let golden = read(&dir.join(format!("{name}.fmt.golden")));
		outcomes.push(Outcome::grade(
			format!("go_jsonnet/{name}"),
			&golden,
			&actual,
		));
	}

	true
}

/// The ratchet.
fn reconcile(outcomes: &[Outcome], graded_namespaces: &BTreeSet<&str>) {
	let quarantined = load_quarantine();

	let mut seen: BTreeSet<&str> = BTreeSet::new();
	for outcome in outcomes {
		assert!(
			seen.insert(outcome.id.as_str()),
			"two fixtures share the id {:?}",
			outcome.id
		);
	}

	let mut unexpected_failures: Vec<String> = Vec::new();
	let mut newly_passing: Vec<String> = Vec::new();
	for outcome in outcomes {
		let listed = quarantined.contains_key(&outcome.id);
		if !outcome.passed && !listed {
			unexpected_failures.push(format!("{}{}", outcome.id, outcome.detail));
		}
		if outcome.passed && listed {
			newly_passing.push(outcome.id.clone());
		}
	}

	let stale: Vec<&str> = quarantined
		.keys()
		.map(String::as_str)
		.filter(|id| !seen.contains(id))
		.filter(|id| {
			// Only reconcile namespaces this run actually graded.
			id.split_once('/')
				.is_some_and(|(namespace, _)| graded_namespaces.contains(namespace))
		})
		.collect();

	let mut report = String::new();
	if !unexpected_failures.is_empty() {
		write!(
			report,
			"\n{} fixture(s) fail and are not in quarantine.toml. Fix them, or add an entry with \
			 a reason:\n  {}\n",
			unexpected_failures.len(),
			unexpected_failures.join("\n  ")
		)
		.expect("writing to a String cannot fail");
	}
	if !newly_passing.is_empty() {
		write!(
			report,
			"\n{} quarantined fixture(s) now pass. Delete their entries from quarantine.toml — \
			 the list may only shrink:\n  {}\n",
			newly_passing.len(),
			newly_passing.join("\n  ")
		)
		.expect("writing to a String cannot fail");
	}
	if !stale.is_empty() {
		write!(
			report,
			"\n{} quarantine.toml entr(ies) name no fixture. Delete them:\n  {}\n",
			stale.len(),
			stale.join("\n  ")
		)
		.expect("writing to a String cannot fail");
	}

	assert!(report.is_empty(), "{report}");

	let quarantined_count = outcomes
		.iter()
		.filter(|outcome| quarantined.contains_key(&outcome.id))
		.count();
	eprintln!(
		"fmt fixtures: {} graded, {} passing, {quarantined_count} quarantined",
		outcomes.len(),
		outcomes.len() - quarantined_count
	);
}

#[test]
fn fixtures_match_tk_and_the_quarantine_list_only_shrinks() {
	let mut outcomes = Vec::new();
	let mut graded_namespaces = BTreeSet::new();

	grade_no_implicit_plus(&mut outcomes);
	graded_namespaces.insert("no_implicit_plus");

	grade_parse_errors(&mut outcomes);
	graded_namespaces.insert("parse_errors");

	if grade_go_jsonnet(&mut outcomes) {
		graded_namespaces.insert("go_jsonnet");
	}

	reconcile(&outcomes, &graded_namespaces);
}
