[package]
name = "rtk-jsonnetfmt"
description = "A port of go-jsonnet's formatter, and of Tanka's Jsonnet file discovery, for tk parity"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
rtk-gobwas-glob.workspace = true
thiserror.workspace = true
walkdir = "2.5"

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
toml = "0.8"

[lints]
workspace = true
