//! Version constraints as `github.com/Masterminds/semver` v1.5.0 reads them.
//!
//! Tanka links that library to interpret `spec.expectVersions.tanka`, and its
//! constraint syntax is not the one the `semver` crate implements. The
//! differences are not decorative:
//!
//! - A bare `1.2.3` means *exactly* `1.2.3` here, and `^1.2.3` to the `semver`
//!   crate.
//! - `^` is major-only, so `^0.1.2` admits `0.38.0`. Both the `semver` crate and
//!   npm stop at `0.2.0`.
//! - `||` separates alternatives, and `x`/`X`/`*` stand in for a number, neither
//!   of which the `semver` crate accepts at all.
//!
//! So this is a port rather than a translation: handing the text to another
//! implementation would quietly answer a different question. The port is checked
//! against a table of answers generated by the Go library itself — see
//! `testdata/masterminds-v1.5.0.json`.

use std::sync::LazyLock;

use regex::Regex;
use thiserror::Error;

/// A constraint Masterminds cannot read.
///
/// Worded as the Go library words it, because Tanka puts the text straight into
/// its own message.
#[derive(Debug, Error)]
#[error("improper constraint: {text}")]
pub struct ImproperConstraint {
	text: String,
}

/// One or more alternatives, each a set of constraints that must all hold.
///
/// Mirrors Masterminds' `Constraints`: `||` separates alternatives and `,`
/// separates the constraints within one.
#[derive(Clone, Debug)]
pub struct Constraints(Vec<Vec<Constraint>>);

impl Constraints {
	/// Read a constraint expression.
	pub fn parse(text: &str) -> Result<Constraints, ImproperConstraint> {
		let rewritten = rewrite_ranges(text);

		let mut alternatives = Vec::new();
		for alternative in rewritten.split("||") {
			let mut constraints = Vec::new();
			for term in alternative.split(',') {
				constraints.push(Constraint::parse(term)?);
			}
			alternatives.push(constraints);
		}

		Ok(Constraints(alternatives))
	}

	/// Whether `version` satisfies any alternative.
	#[must_use]
	pub fn matches(&self, version: &semver::Version) -> bool {
		self.0.iter().any(|alternative| {
			alternative
				.iter()
				.all(|constraint| constraint.matches(version))
		})
	}
}

/// The comparison a constraint asks for.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Operator {
	/// `=`, or nothing at all — which becomes a tilde once wildcards are in play.
	Equal,
	NotEqual,
	Greater,
	GreaterOrEqual,
	Less,
	LessOrEqual,
	Tilde,
	Caret,
}

impl Operator {
	fn parse(text: &str) -> Option<Operator> {
		Some(match text {
			"" | "=" => Operator::Equal,
			"!=" => Operator::NotEqual,
			">" => Operator::Greater,
			">=" | "=>" => Operator::GreaterOrEqual,
			"<" => Operator::Less,
			"<=" | "=<" => Operator::LessOrEqual,
			"~" | "~>" => Operator::Tilde,
			"^" => Operator::Caret,
			_ => return None,
		})
	}
}

/// A single comparison against one version.
#[derive(Clone, Debug)]
struct Constraint {
	operator: Operator,
	/// The version compared against, with any wildcard replaced by zero.
	version: semver::Version,
	/// Whether the text left any part of the version unsaid.
	dirty: bool,
	/// Whether it was the minor that went unsaid.
	minor_dirty: bool,
	/// Whether it was the patch that was wildcarded.
	patch_dirty: bool,
}

impl Constraint {
	fn parse(text: &str) -> Result<Constraint, ImproperConstraint> {
		let improper = || ImproperConstraint {
			text: text.trim().to_owned(),
		};

		let captures = TERM.captures(text).ok_or_else(improper)?;
		let group = |index: usize| {
			captures
				.get(index)
				.map_or("", |capture| capture.as_str())
				.to_owned()
		};

		let operator = Operator::parse(&group(1)).ok_or_else(improper)?;
		let (major, minor, patch, prerelease) = (group(2), group(3), group(4), group(5));

		// Exactly Masterminds' `parseConstraint`: a wildcarded or unsaid part
		// zeroes everything below it and records which part it was. Only the
		// first three branches make the constraint dirty — an absent patch does
		// not, because Go leaves the text alone there and lets its own lenient
		// parser read `1.2` as `1.2.0`.
		let (rebuilt, dirty, minor_dirty, patch_dirty) = if is_wildcard(&major) {
			("0.0.0".to_owned(), true, false, false)
		} else if minor.is_empty() || is_wildcard(minor.trim_start_matches('.')) {
			(format!("{major}.0.0{prerelease}"), true, true, false)
		} else if is_wildcard(patch.trim_start_matches('.')) {
			(format!("{major}{minor}.0{prerelease}"), true, false, true)
		} else if patch.is_empty() {
			(format!("{major}{minor}.0{prerelease}"), false, false, false)
		} else {
			(
				format!("{major}{minor}{patch}{prerelease}"),
				false,
				false,
				false,
			)
		};

		Ok(Constraint {
			operator,
			version: semver::Version::parse(&rebuilt).map_err(|_| improper())?,
			dirty,
			minor_dirty,
			patch_dirty,
		})
	}

	fn matches(&self, version: &semver::Version) -> bool {
		// `!=` is the exception: Masterminds applies the prerelease rule only
		// inside its dirty branch, so `!=1.2.3` accepts `1.2.3-alpha` where
		// every other operator would refuse it. The differential test catches
		// this the moment it is "tidied" away.
		if self.operator != Operator::NotEqual && self.excludes_prerelease(version) {
			return false;
		}

		match self.operator {
			Operator::Equal => self.equal(version),
			Operator::NotEqual => self.not_equal(version),
			Operator::Greater => version > &self.version,
			Operator::GreaterOrEqual => version >= &self.version,
			Operator::Less => self.less(version),
			Operator::LessOrEqual => self.less_or_equal(version),
			Operator::Tilde => self.tilde(version),
			Operator::Caret => self.caret(version),
		}
	}

	/// A prerelease is taken as incompatible with a constraint that did not ask
	/// for one, which is why the version compared against must not itself be a
	/// prerelease or almost nothing would match it.
	fn excludes_prerelease(&self, version: &semver::Version) -> bool {
		!version.pre.is_empty() && self.version.pre.is_empty()
	}

	/// `constraintTildeOrEqual`: a wildcard opts into `~`, otherwise equality.
	fn equal(&self, version: &semver::Version) -> bool {
		if self.dirty {
			return self.tilde(version);
		}
		version == &self.version
	}

	fn not_equal(&self, version: &semver::Version) -> bool {
		if !self.dirty {
			return version != &self.version;
		}
		if self.excludes_prerelease(version) {
			return false;
		}
		if self.version.major != version.major {
			return true;
		}
		if self.version.minor != version.minor && !self.minor_dirty {
			return true;
		}
		false
	}

	fn less(&self, version: &semver::Version) -> bool {
		if !self.dirty {
			return version < &self.version;
		}
		if version.major > self.version.major {
			return false;
		}
		if version.minor > self.version.minor && !self.minor_dirty {
			return false;
		}
		true
	}

	fn less_or_equal(&self, version: &semver::Version) -> bool {
		if !self.dirty {
			return version <= &self.version;
		}
		if version.major > self.version.major {
			return false;
		}
		if version.minor > self.version.minor && !self.minor_dirty {
			return false;
		}
		true
	}

	/// `constraintTilde`: same major, and same minor unless the minor was unsaid.
	fn tilde(&self, version: &semver::Version) -> bool {
		if version < &self.version {
			return false;
		}

		// `~0.0.0` accepts anything at or above it. The test is on the minor
		// and patch flags rather than on `dirty`, which is what makes a bare
		// `x` — dirty, but with neither flag set — accept everything.
		if self.version.major == 0
			&& self.version.minor == 0
			&& self.version.patch == 0
			&& !self.minor_dirty
			&& !self.patch_dirty
		{
			return true;
		}

		if version.major != self.version.major {
			return false;
		}
		if version.minor != self.version.minor && !self.minor_dirty {
			return false;
		}
		true
	}

	/// `constraintCaret`: same major and no lower. Major-only, unlike the
	/// `semver` crate and npm, both of which narrow this for `0.x`.
	fn caret(&self, version: &semver::Version) -> bool {
		if version < &self.version {
			return false;
		}
		version.major == self.version.major
	}
}

fn is_wildcard(text: &str) -> bool {
	matches!(text, "x" | "X" | "*")
}

/// Turn `A - B` into `>= A, <= B`, as Masterminds' `rewriteRange` does.
fn rewrite_ranges(text: &str) -> String {
	let mut rewritten = text.to_owned();
	for captures in RANGE.captures_iter(text) {
		let whole = captures.get(0).expect("the whole match").as_str();
		// `VERSION_PATTERN` holds nine groups, so the second half of the range
		// is the eleventh — which is the `v[11]` Go reaches for.
		let (lower, upper) = (&captures[1], &captures[11]);
		rewritten = rewritten.replacen(whole, &format!(">= {lower}, <= {upper}"), 1);
	}
	rewritten
}

/// Masterminds' `cvRegex`: an optional `v`, then up to three parts each of which
/// may be a wildcard, then an optional prerelease and build metadata.
const VERSION_PATTERN: &str = concat!(
	r"v?([0-9xX*]+)(\.[0-9xX*]+)?(\.[0-9xX*]+)?",
	r"(-([0-9A-Za-z\-]+(\.[0-9A-Za-z\-]+)*))?",
	r"(\+([0-9A-Za-z\-]+(\.[0-9A-Za-z\-]+)*))?",
);

/// One constraint: an operator and a version, surrounded by any whitespace.
static TERM: LazyLock<Regex> = LazyLock::new(|| {
	Regex::new(&format!(
		r"^\s*(=|!=|>|<|>=|=>|<=|=<|~|~>|\^|)\s*{VERSION_PATTERN}\s*$"
	))
	.expect("a valid constraint pattern")
});

/// A hyphen range, whose two halves become a pair of constraints.
static RANGE: LazyLock<Regex> = LazyLock::new(|| {
	Regex::new(&format!(
		r"\s*({VERSION_PATTERN})\s+-\s+({VERSION_PATTERN})\s*"
	))
	.expect("a valid range pattern")
});
