[package]
name = "rtk-jsonnet"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
rayon.workspace = true
regex.workspace = true
rtk-jsonnet-core.workspace = true
rtk-jsonnet-helm.workspace = true
rtk-jsonnet-jrsonnet.workspace = true
rtk-spec.workspace = true
thiserror.workspace = true
tracing.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
