[package]
name = "k8s-mock"
version = "0.1.0"
edition = "2021"
description = "Mock Kubernetes API server for testing"

[dependencies]
bon = "3.8.2"
k8s = { path = "../k8s" }
k8s-openapi.workspace = true
kube.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.44"
typed-headers = "0.2.0"
wiremock = "0.6.5"
