//! Grades this port against a table generated by `gobwas/glob` v0.2.3 itself.
//!
//! The table is the oracle, not the library's documentation: the two disagree
//! about separators, and it is the table that decides which files `rtk fmt`
//! touches. `testdata/generate/` holds the generator; regenerate with
//! `make update-glob-truth-table` (needs Go) whenever the pinned version of the
//! library moves.

use std::{fs, path::PathBuf};

use rtk_gobwas_glob::Glob;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Case {
	pattern: String,
	/// The separators passed to `glob.Compile`, as a string of characters.
	/// Absent means none, which is how `tk` compiles every `--exclude`.
	#[serde(default)]
	separators: String,
	/// `glob.Compile`'s message when it rejected the pattern.
	#[serde(default)]
	error: String,
	#[serde(default)]
	matches: Vec<String>,
	#[serde(default)]
	rejects: Vec<String>,
}

fn table_path() -> PathBuf {
	PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata/gobwas-glob-v0.2.3.json")
}

#[test]
fn matches_the_generated_truth_table() {
	let path = table_path();
	let Ok(raw) = fs::read_to_string(&path) else {
		eprintln!(
			"no gobwas/glob truth table at {}; generate it with `make update-glob-truth-table` \
			 (needs Go). Skipping.",
			path.display()
		);
		return;
	};

	let cases: Vec<Case> = serde_json::from_str(&raw).expect("truth table is valid JSON");
	assert!(!cases.is_empty(), "truth table is empty");

	let mut failures: Vec<String> = Vec::new();

	for case in &cases {
		let separators: Vec<char> = case.separators.chars().collect();
		let label = if separators.is_empty() {
			format!("{:?}", case.pattern)
		} else {
			format!("{:?} sep {:?}", case.pattern, case.separators)
		};

		let compiled = Glob::with_separators(&case.pattern, &separators);

		if !case.error.is_empty() {
			match compiled {
				Ok(_) => failures.push(format!(
					"{label}: gobwas rejected it with {:?}, this port accepted it",
					case.error
				)),
				Err(err) if err.message() != case.error => failures.push(format!(
					"{label}: gobwas said {:?}, this port said {:?}",
					case.error,
					err.message()
				)),
				Err(_) => {}
			}
			continue;
		}

		let glob = match compiled {
			Ok(glob) => glob,
			Err(err) => {
				failures.push(format!(
					"{label}: gobwas accepted it, this port rejected it with {:?}",
					err.message()
				));
				continue;
			}
		};

		for subject in &case.matches {
			if !glob.is_match(subject) {
				failures.push(format!("{label}: should match {subject:?}, did not"));
			}
		}
		for subject in &case.rejects {
			if glob.is_match(subject) {
				failures.push(format!("{label}: should not match {subject:?}, did"));
			}
		}
	}

	assert!(
		failures.is_empty(),
		"{} of {} cases diverge from gobwas/glob:\n{}",
		failures.len(),
		cases.len(),
		failures.join("\n")
	);
}
