//! Every answer in this test came out of `github.com/Masterminds/semver`
//! v1.5.0 — the library and version Tanka links — rather than out of a reading
//! of its documentation.
//!
//! `testdata/masterminds-v1.5.0.json` was generated by `testdata/generate`, a
//! small Go program that calls `NewConstraint` and `Check` over a corpus of
//! constraints and versions and records what it got, including the exact text of
//! every parse failure. The table is committed so this needs no Go toolchain and
//! no network; the generator is committed so it can be regenerated when Tanka
//! changes which version of the library it links.
//!
//! It has already earned its keep. Four divergences that a reading of the
//! documentation would have shipped: `!=` applies the prerelease rule only when
//! the constraint is dirty; the tilde's `~0.0.0` case tests the minor and patch
//! flags rather than `dirty`; an absent patch is not dirty, because Go leaves
//! `1.2` to its own lenient parser; and a hyphen range takes its upper bound
//! from the eleventh capture group.

use std::path::Path;

use serde::Deserialize;

use rtk_masterminds::Constraints;

#[derive(Debug, Deserialize)]
struct Case {
	constraint: String,
	/// The parse error Masterminds gave, when it refused the constraint.
	#[serde(default)]
	error: Option<String>,
	/// Versions it accepted.
	#[serde(default)]
	matches: Vec<String>,
	/// Versions it refused.
	#[serde(default)]
	rejects: Vec<String>,
}

fn corpus() -> Vec<Case> {
	let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("testdata/masterminds-v1.5.0.json");
	let text = std::fs::read_to_string(&path)
		.unwrap_or_else(|error| panic!("reading {}: {error}", path.display()));
	serde_json::from_str(&text).expect("the truth table is valid JSON")
}

#[test]
fn agrees_with_masterminds_on_every_case() {
	let corpus = corpus();
	assert!(corpus.len() > 40, "the corpus should be substantial");

	let mut checked = 0_usize;
	for case in &corpus {
		let parsed = Constraints::parse(&case.constraint);

		if let Some(expected) = &case.error {
			let error = parsed
				.as_ref()
				.err()
				.unwrap_or_else(|| panic!("{:?} should not parse", case.constraint));
			assert_eq!(
				&error.to_string(),
				expected,
				"wrong parse error for {:?}",
				case.constraint
			);
			checked += 1;
			continue;
		}

		let parsed =
			parsed.unwrap_or_else(|error| panic!("{:?} should parse: {error}", case.constraint));

		for version in &case.matches {
			let version = semver::Version::parse(version).expect("a corpus version");
			assert!(
				parsed.matches(&version),
				"{:?} should accept {version}, as Masterminds does",
				case.constraint
			);
			checked += 1;
		}
		for version in &case.rejects {
			let version = semver::Version::parse(version).expect("a corpus version");
			assert!(
				!parsed.matches(&version),
				"{:?} should refuse {version}, as Masterminds does",
				case.constraint
			);
			checked += 1;
		}
	}

	assert!(
		checked > 1_000,
		"only {checked} comparisons were checked; has the table been truncated?"
	);
}

/// The differences that make this a port rather than a translation. Each is
/// asserted directly, so a future "simplification" onto the `semver` crate
/// fails here with the reason spelled out.
#[test]
fn differs_from_the_semver_crate_where_masterminds_does() {
	let exactly = Constraints::parse("1.2.3").expect("a bare version");
	assert!(exactly.matches(&semver::Version::parse("1.2.3").unwrap()));
	assert!(
		!exactly.matches(&semver::Version::parse("1.2.4").unwrap()),
		"a bare constraint is equality here, where the semver crate reads a caret"
	);

	let caret = Constraints::parse("^0.1.2").expect("a caret");
	assert!(
		caret.matches(&semver::Version::parse("0.38.0").unwrap()),
		"^ is major-only here; the semver crate and npm both stop at 0.2.0"
	);

	let alternatives = Constraints::parse(">= 0.0.0 || < 0.0.0").expect("alternatives");
	assert!(
		alternatives.matches(&semver::Version::parse("0.38.0").unwrap()),
		"|| is not syntax the semver crate can even parse"
	);

	let wildcard = Constraints::parse("1.x").expect("a wildcard");
	assert!(wildcard.matches(&semver::Version::parse("1.4.0").unwrap()));
	assert!(!wildcard.matches(&semver::Version::parse("2.0.0").unwrap()));

	let prerelease = Constraints::parse(">=1.0.0").expect("an ordinary constraint");
	assert!(
		!prerelease.matches(&semver::Version::parse("1.2.3-alpha").unwrap()),
		"a prerelease never satisfies a constraint that did not ask for one"
	);
}
