{{- range $i := until (int .Values.itemCount) }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-cron-{{ $i }}
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ include "bench.heavyHash" (dict "seed" (printf "%s-%d-cron" $.Release.Name $i) "rounds" $.Values.hashRounds) }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: job
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
              env:
                {{- range $e := until (int $.Values.envVars) }}
                - name: VAR_{{ $e }}
                  value: {{ sha256sum (printf "%s-%d-cronenv-%d" $.Release.Name $i $e) | quote }}
                {{- end }}
{{- end }}
