{{- range $i := until (int .Values.itemCount) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}-sa-{{ $i }}
  labels:
    {{- range $k := until (int $.Values.labelCount) }}
    label-{{ $k }}: {{ sha256sum (printf "%s-%d-sa-%d" $.Release.Name $i $k) | trunc 32 }}
    {{- end }}
  annotations:
    bench/big-config: |
      {{- toYaml $.Values.bigConfig | nindent 6 }}
{{- end }}
